version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "mix"
    directory: "/elixir"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "daily"
