// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: execution_requested.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GroupId     string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *Fg) Reset() {
	*x = Fg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_execution_requested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fg) ProtoMessage() {}

func (x *Fg) ProtoReflect() protoreflect.Message {
	mi := &file_execution_requested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fg.ProtoReflect.Descriptor instead.
func (*Fg) Descriptor() ([]byte, []int) {
	return file_execution_requested_proto_rawDescGZIP(), []int{0}
}

func (x *Fg) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Fg) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_execution_requested_proto protoreflect.FileDescriptor

var file_execution_requested_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x72, 0x65,
	0x6e, 0x74, 0x6f, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x42, 0x0a,
	0x02, 0x66, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_execution_requested_proto_rawDescOnce sync.Once
	file_execution_requested_proto_rawDescData = file_execution_requested_proto_rawDesc
)

func file_execution_requested_proto_rawDescGZIP() []byte {
	file_execution_requested_proto_rawDescOnce.Do(func() {
		file_execution_requested_proto_rawDescData = protoimpl.X.CompressGZIP(file_execution_requested_proto_rawDescData)
	})
	return file_execution_requested_proto_rawDescData
}

var file_execution_requested_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_execution_requested_proto_goTypes = []interface{}{
	(*Fg)(nil), // 0: trento.checks.v1.fg
}
var file_execution_requested_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_execution_requested_proto_init() }
func file_execution_requested_proto_init() {
	if File_execution_requested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_execution_requested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_execution_requested_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_execution_requested_proto_goTypes,
		DependencyIndexes: file_execution_requested_proto_depIdxs,
		MessageInfos:      file_execution_requested_proto_msgTypes,
	}.Build()
	File_execution_requested_proto = out.File
	file_execution_requested_proto_rawDesc = nil
	file_execution_requested_proto_goTypes = nil
	file_execution_requested_proto_depIdxs = nil
}
