// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/check_customization_reset.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCustomizationReset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckId    string `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	GroupId    string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TargetType string `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
}

func (x *CheckCustomizationReset) Reset() {
	*x = CheckCustomizationReset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_check_customization_reset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCustomizationReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCustomizationReset) ProtoMessage() {}

func (x *CheckCustomizationReset) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_check_customization_reset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCustomizationReset.ProtoReflect.Descriptor instead.
func (*CheckCustomizationReset) Descriptor() ([]byte, []int) {
	return file_protobuf_check_customization_reset_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCustomizationReset) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *CheckCustomizationReset) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CheckCustomizationReset) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

var File_protobuf_check_customization_reset_proto protoreflect.FileDescriptor

var file_protobuf_check_customization_reset_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x54, 0x72, 0x65, 0x6e,
	0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31, 0x22, 0x70, 0x0a, 0x17,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0a,
	0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_check_customization_reset_proto_rawDescOnce sync.Once
	file_protobuf_check_customization_reset_proto_rawDescData = file_protobuf_check_customization_reset_proto_rawDesc
)

func file_protobuf_check_customization_reset_proto_rawDescGZIP() []byte {
	file_protobuf_check_customization_reset_proto_rawDescOnce.Do(func() {
		file_protobuf_check_customization_reset_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_check_customization_reset_proto_rawDescData)
	})
	return file_protobuf_check_customization_reset_proto_rawDescData
}

var file_protobuf_check_customization_reset_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_check_customization_reset_proto_goTypes = []interface{}{
	(*CheckCustomizationReset)(nil), // 0: Trento.Checks.V1.CheckCustomizationReset
}
var file_protobuf_check_customization_reset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_check_customization_reset_proto_init() }
func file_protobuf_check_customization_reset_proto_init() {
	if File_protobuf_check_customization_reset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_check_customization_reset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCustomizationReset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_check_customization_reset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_check_customization_reset_proto_goTypes,
		DependencyIndexes: file_protobuf_check_customization_reset_proto_depIdxs,
		MessageInfos:      file_protobuf_check_customization_reset_proto_msgTypes,
	}.Build()
	File_protobuf_check_customization_reset_proto = out.File
	file_protobuf_check_customization_reset_proto_rawDesc = nil
	file_protobuf_check_customization_reset_proto_goTypes = nil
	file_protobuf_check_customization_reset_proto_depIdxs = nil
}
