// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/check_custom_value.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCustomValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*CheckCustomValue_StringValue
	//	*CheckCustomValue_IntValue
	//	*CheckCustomValue_BoolValue
	Value         isCheckCustomValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCustomValue) Reset() {
	*x = CheckCustomValue{}
	mi := &file_protobuf_check_custom_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCustomValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCustomValue) ProtoMessage() {}

func (x *CheckCustomValue) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_check_custom_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCustomValue.ProtoReflect.Descriptor instead.
func (*CheckCustomValue) Descriptor() ([]byte, []int) {
	return file_protobuf_check_custom_value_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCustomValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckCustomValue) GetValue() isCheckCustomValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CheckCustomValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*CheckCustomValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *CheckCustomValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*CheckCustomValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *CheckCustomValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*CheckCustomValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isCheckCustomValue_Value interface {
	isCheckCustomValue_Value()
}

type CheckCustomValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type CheckCustomValue_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type CheckCustomValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*CheckCustomValue_StringValue) isCheckCustomValue_Value() {}

func (*CheckCustomValue_IntValue) isCheckCustomValue_Value() {}

func (*CheckCustomValue_BoolValue) isCheckCustomValue_Value() {}

var File_protobuf_check_custom_value_proto protoreflect.FileDescriptor

const file_protobuf_check_custom_value_proto_rawDesc = "" +
	"\n" +
	"!protobuf/check_custom_value.proto\x12\x10Trento.Checks.V1\"\x94\x01\n" +
	"\x10CheckCustomValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05valueB\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_check_custom_value_proto_rawDescOnce sync.Once
	file_protobuf_check_custom_value_proto_rawDescData []byte
)

func file_protobuf_check_custom_value_proto_rawDescGZIP() []byte {
	file_protobuf_check_custom_value_proto_rawDescOnce.Do(func() {
		file_protobuf_check_custom_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_check_custom_value_proto_rawDesc), len(file_protobuf_check_custom_value_proto_rawDesc)))
	})
	return file_protobuf_check_custom_value_proto_rawDescData
}

var file_protobuf_check_custom_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_check_custom_value_proto_goTypes = []any{
	(*CheckCustomValue)(nil), // 0: Trento.Checks.V1.CheckCustomValue
}
var file_protobuf_check_custom_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_check_custom_value_proto_init() }
func file_protobuf_check_custom_value_proto_init() {
	if File_protobuf_check_custom_value_proto != nil {
		return
	}
	file_protobuf_check_custom_value_proto_msgTypes[0].OneofWrappers = []any{
		(*CheckCustomValue_StringValue)(nil),
		(*CheckCustomValue_IntValue)(nil),
		(*CheckCustomValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_check_custom_value_proto_rawDesc), len(file_protobuf_check_custom_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_check_custom_value_proto_goTypes,
		DependencyIndexes: file_protobuf_check_custom_value_proto_depIdxs,
		MessageInfos:      file_protobuf_check_custom_value_proto_msgTypes,
	}.Build()
	File_protobuf_check_custom_value_proto = out.File
	file_protobuf_check_custom_value_proto_goTypes = nil
	file_protobuf_check_custom_value_proto_depIdxs = nil
}
