// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/check_customization_reset.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCustomizationReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCustomizationReset) Reset() {
	*x = CheckCustomizationReset{}
	mi := &file_protobuf_check_customization_reset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCustomizationReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCustomizationReset) ProtoMessage() {}

func (x *CheckCustomizationReset) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_check_customization_reset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCustomizationReset.ProtoReflect.Descriptor instead.
func (*CheckCustomizationReset) Descriptor() ([]byte, []int) {
	return file_protobuf_check_customization_reset_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCustomizationReset) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *CheckCustomizationReset) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CheckCustomizationReset) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

var File_protobuf_check_customization_reset_proto protoreflect.FileDescriptor

const file_protobuf_check_customization_reset_proto_rawDesc = "" +
	"\n" +
	"(protobuf/check_customization_reset.proto\x12\x10Trento.Checks.V1\"p\n" +
	"\x17CheckCustomizationReset\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetTypeB\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_check_customization_reset_proto_rawDescOnce sync.Once
	file_protobuf_check_customization_reset_proto_rawDescData []byte
)

func file_protobuf_check_customization_reset_proto_rawDescGZIP() []byte {
	file_protobuf_check_customization_reset_proto_rawDescOnce.Do(func() {
		file_protobuf_check_customization_reset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_check_customization_reset_proto_rawDesc), len(file_protobuf_check_customization_reset_proto_rawDesc)))
	})
	return file_protobuf_check_customization_reset_proto_rawDescData
}

var file_protobuf_check_customization_reset_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_check_customization_reset_proto_goTypes = []any{
	(*CheckCustomizationReset)(nil), // 0: Trento.Checks.V1.CheckCustomizationReset
}
var file_protobuf_check_customization_reset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_check_customization_reset_proto_init() }
func file_protobuf_check_customization_reset_proto_init() {
	if File_protobuf_check_customization_reset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_check_customization_reset_proto_rawDesc), len(file_protobuf_check_customization_reset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_check_customization_reset_proto_goTypes,
		DependencyIndexes: file_protobuf_check_customization_reset_proto_depIdxs,
		MessageInfos:      file_protobuf_check_customization_reset_proto_msgTypes,
	}.Build()
	File_protobuf_check_customization_reset_proto = out.File
	file_protobuf_check_customization_reset_proto_goTypes = nil
	file_protobuf_check_customization_reset_proto_depIdxs = nil
}
