// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/check_custom_value.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCustomValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//
	//	*CheckCustomValue_StringValue
	//	*CheckCustomValue_IntValue
	//	*CheckCustomValue_BoolValue
	Value isCheckCustomValue_Value `protobuf_oneof:"value"`
}

func (x *CheckCustomValue) Reset() {
	*x = CheckCustomValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_check_custom_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCustomValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCustomValue) ProtoMessage() {}

func (x *CheckCustomValue) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_check_custom_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCustomValue.ProtoReflect.Descriptor instead.
func (*CheckCustomValue) Descriptor() ([]byte, []int) {
	return file_protobuf_check_custom_value_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCustomValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *CheckCustomValue) GetValue() isCheckCustomValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CheckCustomValue) GetStringValue() string {
	if x, ok := x.GetValue().(*CheckCustomValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *CheckCustomValue) GetIntValue() int32 {
	if x, ok := x.GetValue().(*CheckCustomValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *CheckCustomValue) GetBoolValue() bool {
	if x, ok := x.GetValue().(*CheckCustomValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

type isCheckCustomValue_Value interface {
	isCheckCustomValue_Value()
}

type CheckCustomValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type CheckCustomValue_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type CheckCustomValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*CheckCustomValue_StringValue) isCheckCustomValue_Value() {}

func (*CheckCustomValue_IntValue) isCheckCustomValue_Value() {}

func (*CheckCustomValue_BoolValue) isCheckCustomValue_Value() {}

var File_protobuf_check_custom_value_proto protoreflect.FileDescriptor

var file_protobuf_check_custom_value_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x73, 0x2e, 0x56, 0x31, 0x22, 0x94, 0x01, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_check_custom_value_proto_rawDescOnce sync.Once
	file_protobuf_check_custom_value_proto_rawDescData = file_protobuf_check_custom_value_proto_rawDesc
)

func file_protobuf_check_custom_value_proto_rawDescGZIP() []byte {
	file_protobuf_check_custom_value_proto_rawDescOnce.Do(func() {
		file_protobuf_check_custom_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_check_custom_value_proto_rawDescData)
	})
	return file_protobuf_check_custom_value_proto_rawDescData
}

var file_protobuf_check_custom_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_check_custom_value_proto_goTypes = []interface{}{
	(*CheckCustomValue)(nil), // 0: Trento.Checks.V1.CheckCustomValue
}
var file_protobuf_check_custom_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_check_custom_value_proto_init() }
func file_protobuf_check_custom_value_proto_init() {
	if File_protobuf_check_custom_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_check_custom_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCustomValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_check_custom_value_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CheckCustomValue_StringValue)(nil),
		(*CheckCustomValue_IntValue)(nil),
		(*CheckCustomValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_check_custom_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_check_custom_value_proto_goTypes,
		DependencyIndexes: file_protobuf_check_custom_value_proto_depIdxs,
		MessageInfos:      file_protobuf_check_custom_value_proto_msgTypes,
	}.Build()
	File_protobuf_check_custom_value_proto = out.File
	file_protobuf_check_custom_value_proto_rawDesc = nil
	file_protobuf_check_custom_value_proto_goTypes = nil
	file_protobuf_check_custom_value_proto_depIdxs = nil
}
