// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/check_customization_applied.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCustomizationApplied struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckId      string              `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	GroupId      string              `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TargetType   string              `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	CustomValues []*CheckCustomValue `protobuf:"bytes,4,rep,name=custom_values,json=customValues,proto3" json:"custom_values,omitempty"`
}

func (x *CheckCustomizationApplied) Reset() {
	*x = CheckCustomizationApplied{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_check_customization_applied_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCustomizationApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCustomizationApplied) ProtoMessage() {}

func (x *CheckCustomizationApplied) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_check_customization_applied_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCustomizationApplied.ProtoReflect.Descriptor instead.
func (*CheckCustomizationApplied) Descriptor() ([]byte, []int) {
	return file_protobuf_check_customization_applied_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCustomizationApplied) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *CheckCustomizationApplied) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CheckCustomizationApplied) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CheckCustomizationApplied) GetCustomValues() []*CheckCustomValue {
	if x != nil {
		return x.CustomValues
	}
	return nil
}

var File_protobuf_check_customization_applied_proto protoreflect.FileDescriptor

var file_protobuf_check_customization_applied_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x54, 0x72,
	0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31, 0x1a, 0x21,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x47, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42,
	0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_check_customization_applied_proto_rawDescOnce sync.Once
	file_protobuf_check_customization_applied_proto_rawDescData = file_protobuf_check_customization_applied_proto_rawDesc
)

func file_protobuf_check_customization_applied_proto_rawDescGZIP() []byte {
	file_protobuf_check_customization_applied_proto_rawDescOnce.Do(func() {
		file_protobuf_check_customization_applied_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_check_customization_applied_proto_rawDescData)
	})
	return file_protobuf_check_customization_applied_proto_rawDescData
}

var file_protobuf_check_customization_applied_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_check_customization_applied_proto_goTypes = []interface{}{
	(*CheckCustomizationApplied)(nil), // 0: Trento.Checks.V1.CheckCustomizationApplied
	(*CheckCustomValue)(nil),          // 1: Trento.Checks.V1.CheckCustomValue
}
var file_protobuf_check_customization_applied_proto_depIdxs = []int32{
	1, // 0: Trento.Checks.V1.CheckCustomizationApplied.custom_values:type_name -> Trento.Checks.V1.CheckCustomValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_check_customization_applied_proto_init() }
func file_protobuf_check_customization_applied_proto_init() {
	if File_protobuf_check_customization_applied_proto != nil {
		return
	}
	file_protobuf_check_custom_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobuf_check_customization_applied_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCustomizationApplied); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_check_customization_applied_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_check_customization_applied_proto_goTypes,
		DependencyIndexes: file_protobuf_check_customization_applied_proto_depIdxs,
		MessageInfos:      file_protobuf_check_customization_applied_proto_msgTypes,
	}.Build()
	File_protobuf_check_customization_applied_proto = out.File
	file_protobuf_check_customization_applied_proto_rawDesc = nil
	file_protobuf_check_customization_applied_proto_goTypes = nil
	file_protobuf_check_customization_applied_proto_depIdxs = nil
}
