// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/discovery_requested.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryType string                 `protobuf:"bytes,1,opt,name=discovery_type,json=discoveryType,proto3" json:"discovery_type,omitempty"`
	Targets       []string               `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequested) Reset() {
	*x = DiscoveryRequested{}
	mi := &file_protobuf_discovery_requested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequested) ProtoMessage() {}

func (x *DiscoveryRequested) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_discovery_requested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequested.ProtoReflect.Descriptor instead.
func (*DiscoveryRequested) Descriptor() ([]byte, []int) {
	return file_protobuf_discovery_requested_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryRequested) GetDiscoveryType() string {
	if x != nil {
		return x.DiscoveryType
	}
	return ""
}

func (x *DiscoveryRequested) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_protobuf_discovery_requested_proto protoreflect.FileDescriptor

const file_protobuf_discovery_requested_proto_rawDesc = "" +
	"\n" +
	"\"protobuf/discovery_requested.proto\x12\x15Trento.Discoveries.V1\"U\n" +
	"\x12DiscoveryRequested\x12%\n" +
	"\x0ediscovery_type\x18\x01 \x01(\tR\rdiscoveryType\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargetsB\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_discovery_requested_proto_rawDescOnce sync.Once
	file_protobuf_discovery_requested_proto_rawDescData []byte
)

func file_protobuf_discovery_requested_proto_rawDescGZIP() []byte {
	file_protobuf_discovery_requested_proto_rawDescOnce.Do(func() {
		file_protobuf_discovery_requested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_discovery_requested_proto_rawDesc), len(file_protobuf_discovery_requested_proto_rawDesc)))
	})
	return file_protobuf_discovery_requested_proto_rawDescData
}

var file_protobuf_discovery_requested_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_discovery_requested_proto_goTypes = []any{
	(*DiscoveryRequested)(nil), // 0: Trento.Discoveries.V1.DiscoveryRequested
}
var file_protobuf_discovery_requested_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_discovery_requested_proto_init() }
func file_protobuf_discovery_requested_proto_init() {
	if File_protobuf_discovery_requested_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_discovery_requested_proto_rawDesc), len(file_protobuf_discovery_requested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_discovery_requested_proto_goTypes,
		DependencyIndexes: file_protobuf_discovery_requested_proto_depIdxs,
		MessageInfos:      file_protobuf_discovery_requested_proto_msgTypes,
	}.Build()
	File_protobuf_discovery_requested_proto = out.File
	file_protobuf_discovery_requested_proto_goTypes = nil
	file_protobuf_discovery_requested_proto_depIdxs = nil
}
