// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/execution_requested.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionRequested struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ExecutionId   string                     `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GroupId       string                     `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Targets       []*Target                  `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	Env           map[string]*structpb.Value `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TargetType    string                     `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequested) Reset() {
	*x = ExecutionRequested{}
	mi := &file_protobuf_execution_requested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequested) ProtoMessage() {}

func (x *ExecutionRequested) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_execution_requested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequested.ProtoReflect.Descriptor instead.
func (*ExecutionRequested) Descriptor() ([]byte, []int) {
	return file_protobuf_execution_requested_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequested) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionRequested) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ExecutionRequested) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ExecutionRequested) GetEnv() map[string]*structpb.Value {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecutionRequested) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

var File_protobuf_execution_requested_proto protoreflect.FileDescriptor

const file_protobuf_execution_requested_proto_rawDesc = "" +
	"\n" +
	"\"protobuf/execution_requested.proto\x12\x10Trento.Checks.V1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15protobuf/target.proto\"\xb8\x02\n" +
	"\x12ExecutionRequested\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x122\n" +
	"\atargets\x18\x03 \x03(\v2\x18.Trento.Checks.V1.TargetR\atargets\x12?\n" +
	"\x03env\x18\x04 \x03(\v2-.Trento.Checks.V1.ExecutionRequested.EnvEntryR\x03env\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x1aN\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_execution_requested_proto_rawDescOnce sync.Once
	file_protobuf_execution_requested_proto_rawDescData []byte
)

func file_protobuf_execution_requested_proto_rawDescGZIP() []byte {
	file_protobuf_execution_requested_proto_rawDescOnce.Do(func() {
		file_protobuf_execution_requested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_execution_requested_proto_rawDesc), len(file_protobuf_execution_requested_proto_rawDesc)))
	})
	return file_protobuf_execution_requested_proto_rawDescData
}

var file_protobuf_execution_requested_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_execution_requested_proto_goTypes = []any{
	(*ExecutionRequested)(nil), // 0: Trento.Checks.V1.ExecutionRequested
	nil,                        // 1: Trento.Checks.V1.ExecutionRequested.EnvEntry
	(*Target)(nil),             // 2: Trento.Checks.V1.Target
	(*structpb.Value)(nil),     // 3: google.protobuf.Value
}
var file_protobuf_execution_requested_proto_depIdxs = []int32{
	2, // 0: Trento.Checks.V1.ExecutionRequested.targets:type_name -> Trento.Checks.V1.Target
	1, // 1: Trento.Checks.V1.ExecutionRequested.env:type_name -> Trento.Checks.V1.ExecutionRequested.EnvEntry
	3, // 2: Trento.Checks.V1.ExecutionRequested.EnvEntry.value:type_name -> google.protobuf.Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_execution_requested_proto_init() }
func file_protobuf_execution_requested_proto_init() {
	if File_protobuf_execution_requested_proto != nil {
		return
	}
	file_protobuf_target_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_execution_requested_proto_rawDesc), len(file_protobuf_execution_requested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_execution_requested_proto_goTypes,
		DependencyIndexes: file_protobuf_execution_requested_proto_depIdxs,
		MessageInfos:      file_protobuf_execution_requested_proto_msgTypes,
	}.Build()
	File_protobuf_execution_requested_proto = out.File
	file_protobuf_execution_requested_proto_goTypes = nil
	file_protobuf_execution_requested_proto_depIdxs = nil
}
