// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/execution_started.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutionId string    `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GroupId     string    `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Targets     []*Target `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	TargetType  string    `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
}

func (x *ExecutionStarted) Reset() {
	*x = ExecutionStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_execution_started_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStarted) ProtoMessage() {}

func (x *ExecutionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_execution_started_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStarted.ProtoReflect.Descriptor instead.
func (*ExecutionStarted) Descriptor() ([]byte, []int) {
	return file_protobuf_execution_started_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionStarted) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionStarted) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ExecutionStarted) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ExecutionStarted) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

var File_protobuf_execution_started_proto protoreflect.FileDescriptor

var file_protobuf_execution_started_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x74, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x73, 0x2e, 0x76, 0x31, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x10,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x32,
	0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x74, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_execution_started_proto_rawDescOnce sync.Once
	file_protobuf_execution_started_proto_rawDescData = file_protobuf_execution_started_proto_rawDesc
)

func file_protobuf_execution_started_proto_rawDescGZIP() []byte {
	file_protobuf_execution_started_proto_rawDescOnce.Do(func() {
		file_protobuf_execution_started_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_execution_started_proto_rawDescData)
	})
	return file_protobuf_execution_started_proto_rawDescData
}

var file_protobuf_execution_started_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_execution_started_proto_goTypes = []interface{}{
	(*ExecutionStarted)(nil), // 0: trento.checks.v1.ExecutionStarted
	(*Target)(nil),           // 1: trento.checks.v1.Target
}
var file_protobuf_execution_started_proto_depIdxs = []int32{
	1, // 0: trento.checks.v1.ExecutionStarted.targets:type_name -> trento.checks.v1.Target
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_execution_started_proto_init() }
func file_protobuf_execution_started_proto_init() {
	if File_protobuf_execution_started_proto != nil {
		return
	}
	file_protobuf_target_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobuf_execution_started_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_execution_started_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_execution_started_proto_goTypes,
		DependencyIndexes: file_protobuf_execution_started_proto_depIdxs,
		MessageInfos:      file_protobuf_execution_started_proto_msgTypes,
	}.Build()
	File_protobuf_execution_started_proto = out.File
	file_protobuf_execution_started_proto_rawDesc = nil
	file_protobuf_execution_started_proto_goTypes = nil
	file_protobuf_execution_started_proto_depIdxs = nil
}
