// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/facts_gathered.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactError) Reset() {
	*x = FactError{}
	mi := &file_protobuf_facts_gathered_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactError) ProtoMessage() {}

func (x *FactError) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathered_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactError.ProtoReflect.Descriptor instead.
func (*FactError) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathered_proto_rawDescGZIP(), []int{0}
}

func (x *FactError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FactError) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Fact struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	CheckId string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to FactValue:
	//
	//	*Fact_Value
	//	*Fact_ErrorValue
	FactValue     isFact_FactValue `protobuf_oneof:"fact_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fact) Reset() {
	*x = Fact{}
	mi := &file_protobuf_facts_gathered_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathered_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathered_proto_rawDescGZIP(), []int{1}
}

func (x *Fact) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *Fact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fact) GetFactValue() isFact_FactValue {
	if x != nil {
		return x.FactValue
	}
	return nil
}

func (x *Fact) GetValue() *structpb.Value {
	if x != nil {
		if x, ok := x.FactValue.(*Fact_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Fact) GetErrorValue() *FactError {
	if x != nil {
		if x, ok := x.FactValue.(*Fact_ErrorValue); ok {
			return x.ErrorValue
		}
	}
	return nil
}

type isFact_FactValue interface {
	isFact_FactValue()
}

type Fact_Value struct {
	Value *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3,oneof"`
}

type Fact_ErrorValue struct {
	ErrorValue *FactError `protobuf:"bytes,4,opt,name=error_value,json=errorValue,proto3,oneof"`
}

func (*Fact_Value) isFact_FactValue() {}

func (*Fact_ErrorValue) isFact_FactValue() {}

type FactsGathered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FactsGathered []*Fact                `protobuf:"bytes,4,rep,name=facts_gathered,json=factsGathered,proto3" json:"facts_gathered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactsGathered) Reset() {
	*x = FactsGathered{}
	mi := &file_protobuf_facts_gathered_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactsGathered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactsGathered) ProtoMessage() {}

func (x *FactsGathered) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathered_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactsGathered.ProtoReflect.Descriptor instead.
func (*FactsGathered) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathered_proto_rawDescGZIP(), []int{2}
}

func (x *FactsGathered) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *FactsGathered) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FactsGathered) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FactsGathered) GetFactsGathered() []*Fact {
	if x != nil {
		return x.FactsGathered
	}
	return nil
}

var File_protobuf_facts_gathered_proto protoreflect.FileDescriptor

const file_protobuf_facts_gathered_proto_rawDesc = "" +
	"\n" +
	"\x1dprotobuf/facts_gathered.proto\x12\x10Trento.Checks.V1\x1a\x1cgoogle/protobuf/struct.proto\"9\n" +
	"\tFactError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xb3\x01\n" +
	"\x04Fact\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueH\x00R\x05value\x12>\n" +
	"\verror_value\x18\x04 \x01(\v2\x1b.Trento.Checks.V1.FactErrorH\x00R\n" +
	"errorValueB\f\n" +
	"\n" +
	"fact_value\"\xa7\x01\n" +
	"\rFactsGathered\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12=\n" +
	"\x0efacts_gathered\x18\x04 \x03(\v2\x16.Trento.Checks.V1.FactR\rfactsGatheredB\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_facts_gathered_proto_rawDescOnce sync.Once
	file_protobuf_facts_gathered_proto_rawDescData []byte
)

func file_protobuf_facts_gathered_proto_rawDescGZIP() []byte {
	file_protobuf_facts_gathered_proto_rawDescOnce.Do(func() {
		file_protobuf_facts_gathered_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_facts_gathered_proto_rawDesc), len(file_protobuf_facts_gathered_proto_rawDesc)))
	})
	return file_protobuf_facts_gathered_proto_rawDescData
}

var file_protobuf_facts_gathered_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_facts_gathered_proto_goTypes = []any{
	(*FactError)(nil),      // 0: Trento.Checks.V1.FactError
	(*Fact)(nil),           // 1: Trento.Checks.V1.Fact
	(*FactsGathered)(nil),  // 2: Trento.Checks.V1.FactsGathered
	(*structpb.Value)(nil), // 3: google.protobuf.Value
}
var file_protobuf_facts_gathered_proto_depIdxs = []int32{
	3, // 0: Trento.Checks.V1.Fact.value:type_name -> google.protobuf.Value
	0, // 1: Trento.Checks.V1.Fact.error_value:type_name -> Trento.Checks.V1.FactError
	1, // 2: Trento.Checks.V1.FactsGathered.facts_gathered:type_name -> Trento.Checks.V1.Fact
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_facts_gathered_proto_init() }
func file_protobuf_facts_gathered_proto_init() {
	if File_protobuf_facts_gathered_proto != nil {
		return
	}
	file_protobuf_facts_gathered_proto_msgTypes[1].OneofWrappers = []any{
		(*Fact_Value)(nil),
		(*Fact_ErrorValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_facts_gathered_proto_rawDesc), len(file_protobuf_facts_gathered_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_facts_gathered_proto_goTypes,
		DependencyIndexes: file_protobuf_facts_gathered_proto_depIdxs,
		MessageInfos:      file_protobuf_facts_gathered_proto_msgTypes,
	}.Build()
	File_protobuf_facts_gathered_proto = out.File
	file_protobuf_facts_gathered_proto_goTypes = nil
	file_protobuf_facts_gathered_proto_depIdxs = nil
}
