// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.4
// source: protobuf/facts_gathering_requested.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckId  string `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gatherer string `protobuf:"bytes,3,opt,name=gatherer,proto3" json:"gatherer,omitempty"`
	Argument string `protobuf:"bytes,4,opt,name=argument,proto3" json:"argument,omitempty"`
}

func (x *FactRequest) Reset() {
	*x = FactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactRequest) ProtoMessage() {}

func (x *FactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactRequest.ProtoReflect.Descriptor instead.
func (*FactRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathering_requested_proto_rawDescGZIP(), []int{0}
}

func (x *FactRequest) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *FactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactRequest) GetGatherer() string {
	if x != nil {
		return x.Gatherer
	}
	return ""
}

func (x *FactRequest) GetArgument() string {
	if x != nil {
		return x.Argument
	}
	return ""
}

type FactsGatheringRequestedTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId      string         `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FactRequests []*FactRequest `protobuf:"bytes,2,rep,name=fact_requests,json=factRequests,proto3" json:"fact_requests,omitempty"`
}

func (x *FactsGatheringRequestedTarget) Reset() {
	*x = FactsGatheringRequestedTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactsGatheringRequestedTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactsGatheringRequestedTarget) ProtoMessage() {}

func (x *FactsGatheringRequestedTarget) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactsGatheringRequestedTarget.ProtoReflect.Descriptor instead.
func (*FactsGatheringRequestedTarget) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathering_requested_proto_rawDescGZIP(), []int{1}
}

func (x *FactsGatheringRequestedTarget) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FactsGatheringRequestedTarget) GetFactRequests() []*FactRequest {
	if x != nil {
		return x.FactRequests
	}
	return nil
}

type FactsGatheringRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutionId string                           `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GroupId     string                           `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Targets     []*FactsGatheringRequestedTarget `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *FactsGatheringRequested) Reset() {
	*x = FactsGatheringRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactsGatheringRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactsGatheringRequested) ProtoMessage() {}

func (x *FactsGatheringRequested) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactsGatheringRequested.ProtoReflect.Descriptor instead.
func (*FactsGatheringRequested) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathering_requested_proto_rawDescGZIP(), []int{2}
}

func (x *FactsGatheringRequested) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *FactsGatheringRequested) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FactsGatheringRequested) GetTargets() []*FactsGatheringRequestedTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_protobuf_facts_gathering_requested_proto protoreflect.FileDescriptor

var file_protobuf_facts_gathering_requested_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x73,
	0x5f, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x54, 0x72, 0x65, 0x6e,
	0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31, 0x22, 0x74, 0x0a, 0x0b,
	0x46, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x7e, 0x0a, 0x1d, 0x46, 0x61, 0x63, 0x74, 0x73, 0x47, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x42,
	0x0a, 0x0d, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x17, 0x46, 0x61, 0x63, 0x74, 0x73, 0x47, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31,
	0x2e, 0x46, 0x61, 0x63, 0x74, 0x73, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_facts_gathering_requested_proto_rawDescOnce sync.Once
	file_protobuf_facts_gathering_requested_proto_rawDescData = file_protobuf_facts_gathering_requested_proto_rawDesc
)

func file_protobuf_facts_gathering_requested_proto_rawDescGZIP() []byte {
	file_protobuf_facts_gathering_requested_proto_rawDescOnce.Do(func() {
		file_protobuf_facts_gathering_requested_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_facts_gathering_requested_proto_rawDescData)
	})
	return file_protobuf_facts_gathering_requested_proto_rawDescData
}

var file_protobuf_facts_gathering_requested_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_facts_gathering_requested_proto_goTypes = []interface{}{
	(*FactRequest)(nil),                   // 0: Trento.Checks.V1.FactRequest
	(*FactsGatheringRequestedTarget)(nil), // 1: Trento.Checks.V1.FactsGatheringRequestedTarget
	(*FactsGatheringRequested)(nil),       // 2: Trento.Checks.V1.FactsGatheringRequested
}
var file_protobuf_facts_gathering_requested_proto_depIdxs = []int32{
	0, // 0: Trento.Checks.V1.FactsGatheringRequestedTarget.fact_requests:type_name -> Trento.Checks.V1.FactRequest
	1, // 1: Trento.Checks.V1.FactsGatheringRequested.targets:type_name -> Trento.Checks.V1.FactsGatheringRequestedTarget
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_facts_gathering_requested_proto_init() }
func file_protobuf_facts_gathering_requested_proto_init() {
	if File_protobuf_facts_gathering_requested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_facts_gathering_requested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_facts_gathering_requested_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactsGatheringRequestedTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_facts_gathering_requested_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactsGatheringRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_facts_gathering_requested_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_facts_gathering_requested_proto_goTypes,
		DependencyIndexes: file_protobuf_facts_gathering_requested_proto_depIdxs,
		MessageInfos:      file_protobuf_facts_gathering_requested_proto_msgTypes,
	}.Build()
	File_protobuf_facts_gathering_requested_proto = out.File
	file_protobuf_facts_gathering_requested_proto_rawDesc = nil
	file_protobuf_facts_gathering_requested_proto_goTypes = nil
	file_protobuf_facts_gathering_requested_proto_depIdxs = nil
}
