// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/facts_gathered.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *FactError) Reset() {
	*x = FactError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_facts_gathered_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactError) ProtoMessage() {}

func (x *FactError) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathered_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactError.ProtoReflect.Descriptor instead.
func (*FactError) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathered_proto_rawDescGZIP(), []int{0}
}

func (x *FactError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FactError) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Fact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckId string `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to FactValue:
	//	*Fact_Value
	//	*Fact_ErrorValue
	FactValue isFact_FactValue `protobuf_oneof:"fact_value"`
}

func (x *Fact) Reset() {
	*x = Fact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_facts_gathered_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathered_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathered_proto_rawDescGZIP(), []int{1}
}

func (x *Fact) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *Fact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Fact) GetFactValue() isFact_FactValue {
	if m != nil {
		return m.FactValue
	}
	return nil
}

func (x *Fact) GetValue() *structpb.Value {
	if x, ok := x.GetFactValue().(*Fact_Value); ok {
		return x.Value
	}
	return nil
}

func (x *Fact) GetErrorValue() *FactError {
	if x, ok := x.GetFactValue().(*Fact_ErrorValue); ok {
		return x.ErrorValue
	}
	return nil
}

type isFact_FactValue interface {
	isFact_FactValue()
}

type Fact_Value struct {
	Value *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3,oneof"`
}

type Fact_ErrorValue struct {
	ErrorValue *FactError `protobuf:"bytes,4,opt,name=error_value,json=errorValue,proto3,oneof"`
}

func (*Fact_Value) isFact_FactValue() {}

func (*Fact_ErrorValue) isFact_FactValue() {}

type FactsGathered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutionId   string  `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GroupId       string  `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AgentId       string  `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FactsGathered []*Fact `protobuf:"bytes,4,rep,name=facts_gathered,json=factsGathered,proto3" json:"facts_gathered,omitempty"`
}

func (x *FactsGathered) Reset() {
	*x = FactsGathered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_facts_gathered_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactsGathered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactsGathered) ProtoMessage() {}

func (x *FactsGathered) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathered_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactsGathered.ProtoReflect.Descriptor instead.
func (*FactsGathered) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathered_proto_rawDescGZIP(), []int{2}
}

func (x *FactsGathered) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *FactsGathered) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FactsGathered) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FactsGathered) GetFactsGathered() []*Fact {
	if x != nil {
		return x.FactsGathered
	}
	return nil
}

var File_protobuf_facts_gathered_proto protoreflect.FileDescriptor

var file_protobuf_facts_gathered_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x73,
	0x5f, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x39, 0x0a, 0x09, 0x46, 0x61, 0x63, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb3, 0x01, 0x0a, 0x04, 0x46,
	0x61, 0x63, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0xa7, 0x01, 0x0a, 0x0d, 0x46, 0x61, 0x63, 0x74, 0x73, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0e, 0x66,
	0x61, 0x63, 0x74, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x52, 0x0d, 0x66, 0x61, 0x63,
	0x74, 0x73, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x65, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_facts_gathered_proto_rawDescOnce sync.Once
	file_protobuf_facts_gathered_proto_rawDescData = file_protobuf_facts_gathered_proto_rawDesc
)

func file_protobuf_facts_gathered_proto_rawDescGZIP() []byte {
	file_protobuf_facts_gathered_proto_rawDescOnce.Do(func() {
		file_protobuf_facts_gathered_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_facts_gathered_proto_rawDescData)
	})
	return file_protobuf_facts_gathered_proto_rawDescData
}

var file_protobuf_facts_gathered_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_facts_gathered_proto_goTypes = []interface{}{
	(*FactError)(nil),      // 0: Trento.Checks.V1.FactError
	(*Fact)(nil),           // 1: Trento.Checks.V1.Fact
	(*FactsGathered)(nil),  // 2: Trento.Checks.V1.FactsGathered
	(*structpb.Value)(nil), // 3: google.protobuf.Value
}
var file_protobuf_facts_gathered_proto_depIdxs = []int32{
	3, // 0: Trento.Checks.V1.Fact.value:type_name -> google.protobuf.Value
	0, // 1: Trento.Checks.V1.Fact.error_value:type_name -> Trento.Checks.V1.FactError
	1, // 2: Trento.Checks.V1.FactsGathered.facts_gathered:type_name -> Trento.Checks.V1.Fact
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_facts_gathered_proto_init() }
func file_protobuf_facts_gathered_proto_init() {
	if File_protobuf_facts_gathered_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_facts_gathered_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_facts_gathered_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_facts_gathered_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactsGathered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_facts_gathered_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Fact_Value)(nil),
		(*Fact_ErrorValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_facts_gathered_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_facts_gathered_proto_goTypes,
		DependencyIndexes: file_protobuf_facts_gathered_proto_depIdxs,
		MessageInfos:      file_protobuf_facts_gathered_proto_msgTypes,
	}.Build()
	File_protobuf_facts_gathered_proto = out.File
	file_protobuf_facts_gathered_proto_rawDesc = nil
	file_protobuf_facts_gathered_proto_goTypes = nil
	file_protobuf_facts_gathered_proto_depIdxs = nil
}
