// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/facts_gathering_requested.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gatherer      string                 `protobuf:"bytes,3,opt,name=gatherer,proto3" json:"gatherer,omitempty"`
	Argument      string                 `protobuf:"bytes,4,opt,name=argument,proto3" json:"argument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactRequest) Reset() {
	*x = FactRequest{}
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactRequest) ProtoMessage() {}

func (x *FactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactRequest.ProtoReflect.Descriptor instead.
func (*FactRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathering_requested_proto_rawDescGZIP(), []int{0}
}

func (x *FactRequest) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *FactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactRequest) GetGatherer() string {
	if x != nil {
		return x.Gatherer
	}
	return ""
}

func (x *FactRequest) GetArgument() string {
	if x != nil {
		return x.Argument
	}
	return ""
}

type FactsGatheringRequestedTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FactRequests  []*FactRequest         `protobuf:"bytes,2,rep,name=fact_requests,json=factRequests,proto3" json:"fact_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactsGatheringRequestedTarget) Reset() {
	*x = FactsGatheringRequestedTarget{}
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactsGatheringRequestedTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactsGatheringRequestedTarget) ProtoMessage() {}

func (x *FactsGatheringRequestedTarget) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactsGatheringRequestedTarget.ProtoReflect.Descriptor instead.
func (*FactsGatheringRequestedTarget) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathering_requested_proto_rawDescGZIP(), []int{1}
}

func (x *FactsGatheringRequestedTarget) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FactsGatheringRequestedTarget) GetFactRequests() []*FactRequest {
	if x != nil {
		return x.FactRequests
	}
	return nil
}

type FactsGatheringRequested struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	ExecutionId   string                           `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GroupId       string                           `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Targets       []*FactsGatheringRequestedTarget `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactsGatheringRequested) Reset() {
	*x = FactsGatheringRequested{}
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactsGatheringRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactsGatheringRequested) ProtoMessage() {}

func (x *FactsGatheringRequested) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_facts_gathering_requested_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactsGatheringRequested.ProtoReflect.Descriptor instead.
func (*FactsGatheringRequested) Descriptor() ([]byte, []int) {
	return file_protobuf_facts_gathering_requested_proto_rawDescGZIP(), []int{2}
}

func (x *FactsGatheringRequested) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *FactsGatheringRequested) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FactsGatheringRequested) GetTargets() []*FactsGatheringRequestedTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_protobuf_facts_gathering_requested_proto protoreflect.FileDescriptor

const file_protobuf_facts_gathering_requested_proto_rawDesc = "" +
	"\n" +
	"(protobuf/facts_gathering_requested.proto\x12\x10Trento.Checks.V1\"t\n" +
	"\vFactRequest\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bgatherer\x18\x03 \x01(\tR\bgatherer\x12\x1a\n" +
	"\bargument\x18\x04 \x01(\tR\bargument\"~\n" +
	"\x1dFactsGatheringRequestedTarget\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12B\n" +
	"\rfact_requests\x18\x02 \x03(\v2\x1d.Trento.Checks.V1.FactRequestR\ffactRequests\"\xa2\x01\n" +
	"\x17FactsGatheringRequested\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12I\n" +
	"\atargets\x18\x03 \x03(\v2/.Trento.Checks.V1.FactsGatheringRequestedTargetR\atargetsB\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_facts_gathering_requested_proto_rawDescOnce sync.Once
	file_protobuf_facts_gathering_requested_proto_rawDescData []byte
)

func file_protobuf_facts_gathering_requested_proto_rawDescGZIP() []byte {
	file_protobuf_facts_gathering_requested_proto_rawDescOnce.Do(func() {
		file_protobuf_facts_gathering_requested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_facts_gathering_requested_proto_rawDesc), len(file_protobuf_facts_gathering_requested_proto_rawDesc)))
	})
	return file_protobuf_facts_gathering_requested_proto_rawDescData
}

var file_protobuf_facts_gathering_requested_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_facts_gathering_requested_proto_goTypes = []any{
	(*FactRequest)(nil),                   // 0: Trento.Checks.V1.FactRequest
	(*FactsGatheringRequestedTarget)(nil), // 1: Trento.Checks.V1.FactsGatheringRequestedTarget
	(*FactsGatheringRequested)(nil),       // 2: Trento.Checks.V1.FactsGatheringRequested
}
var file_protobuf_facts_gathering_requested_proto_depIdxs = []int32{
	0, // 0: Trento.Checks.V1.FactsGatheringRequestedTarget.fact_requests:type_name -> Trento.Checks.V1.FactRequest
	1, // 1: Trento.Checks.V1.FactsGatheringRequested.targets:type_name -> Trento.Checks.V1.FactsGatheringRequestedTarget
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_facts_gathering_requested_proto_init() }
func file_protobuf_facts_gathering_requested_proto_init() {
	if File_protobuf_facts_gathering_requested_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_facts_gathering_requested_proto_rawDesc), len(file_protobuf_facts_gathering_requested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_facts_gathering_requested_proto_goTypes,
		DependencyIndexes: file_protobuf_facts_gathering_requested_proto_depIdxs,
		MessageInfos:      file_protobuf_facts_gathering_requested_proto_msgTypes,
	}.Build()
	File_protobuf_facts_gathering_requested_proto = out.File
	file_protobuf_facts_gathering_requested_proto_goTypes = nil
	file_protobuf_facts_gathering_requested_proto_depIdxs = nil
}
