// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/operation_target.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationTarget struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	AgentId       string                     `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Arguments     map[string]*structpb.Value `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationTarget) Reset() {
	*x = OperationTarget{}
	mi := &file_protobuf_operation_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationTarget) ProtoMessage() {}

func (x *OperationTarget) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationTarget.ProtoReflect.Descriptor instead.
func (*OperationTarget) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_target_proto_rawDescGZIP(), []int{0}
}

func (x *OperationTarget) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *OperationTarget) GetArguments() map[string]*structpb.Value {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_protobuf_operation_target_proto protoreflect.FileDescriptor

const file_protobuf_operation_target_proto_rawDesc = "" +
	"\n" +
	"\x1fprotobuf/operation_target.proto\x12\x14Trento.Operations.V1\x1a\x1cgoogle/protobuf/struct.proto\"\xd6\x01\n" +
	"\x0fOperationTarget\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12R\n" +
	"\targuments\x18\x02 \x03(\v24.Trento.Operations.V1.OperationTarget.ArgumentsEntryR\targuments\x1aT\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_operation_target_proto_rawDescOnce sync.Once
	file_protobuf_operation_target_proto_rawDescData []byte
)

func file_protobuf_operation_target_proto_rawDescGZIP() []byte {
	file_protobuf_operation_target_proto_rawDescOnce.Do(func() {
		file_protobuf_operation_target_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_operation_target_proto_rawDesc), len(file_protobuf_operation_target_proto_rawDesc)))
	})
	return file_protobuf_operation_target_proto_rawDescData
}

var file_protobuf_operation_target_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_operation_target_proto_goTypes = []any{
	(*OperationTarget)(nil), // 0: Trento.Operations.V1.OperationTarget
	nil,                     // 1: Trento.Operations.V1.OperationTarget.ArgumentsEntry
	(*structpb.Value)(nil),  // 2: google.protobuf.Value
}
var file_protobuf_operation_target_proto_depIdxs = []int32{
	1, // 0: Trento.Operations.V1.OperationTarget.arguments:type_name -> Trento.Operations.V1.OperationTarget.ArgumentsEntry
	2, // 1: Trento.Operations.V1.OperationTarget.ArgumentsEntry.value:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_operation_target_proto_init() }
func file_protobuf_operation_target_proto_init() {
	if File_protobuf_operation_target_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_operation_target_proto_rawDesc), len(file_protobuf_operation_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operation_target_proto_goTypes,
		DependencyIndexes: file_protobuf_operation_target_proto_depIdxs,
		MessageInfos:      file_protobuf_operation_target_proto_msgTypes,
	}.Build()
	File_protobuf_operation_target_proto = out.File
	file_protobuf_operation_target_proto_goTypes = nil
	file_protobuf_operation_target_proto_depIdxs = nil
}
