// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/operation_completed.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationResult int32

const (
	OperationResult_UPDATED     OperationResult = 0
	OperationResult_NOT_UPDATED OperationResult = 1
	OperationResult_ROLLED_BACK OperationResult = 2
	OperationResult_FAILED      OperationResult = 3
	OperationResult_ABORTED     OperationResult = 4
	// ALREADY_RUNNING = 5;
	OperationResult_REQUEST_FAILED OperationResult = 6
)

// Enum value maps for OperationResult.
var (
	OperationResult_name = map[int32]string{
		0: "UPDATED",
		1: "NOT_UPDATED",
		2: "ROLLED_BACK",
		3: "FAILED",
		4: "ABORTED",
		6: "REQUEST_FAILED",
	}
	OperationResult_value = map[string]int32{
		"UPDATED":        0,
		"NOT_UPDATED":    1,
		"ROLLED_BACK":    2,
		"FAILED":         3,
		"ABORTED":        4,
		"REQUEST_FAILED": 6,
	}
)

func (x OperationResult) Enum() *OperationResult {
	p := new(OperationResult)
	*p = x
	return p
}

func (x OperationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_operation_completed_proto_enumTypes[0].Descriptor()
}

func (OperationResult) Type() protoreflect.EnumType {
	return &file_protobuf_operation_completed_proto_enumTypes[0]
}

func (x OperationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationResult.Descriptor instead.
func (OperationResult) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_operation_completed_proto_rawDescGZIP(), []int{0}
}

type OperationRequestFailedError int32

const (
	OperationRequestFailedError_ARGUMENTS_MISSING OperationRequestFailedError = 0
	OperationRequestFailedError_TARGETS_MISSING   OperationRequestFailedError = 1
	OperationRequestFailedError_ALREADY_RUNNING   OperationRequestFailedError = 2
	OperationRequestFailedError_UNKNOWN           OperationRequestFailedError = 3
)

// Enum value maps for OperationRequestFailedError.
var (
	OperationRequestFailedError_name = map[int32]string{
		0: "ARGUMENTS_MISSING",
		1: "TARGETS_MISSING",
		2: "ALREADY_RUNNING",
		3: "UNKNOWN",
	}
	OperationRequestFailedError_value = map[string]int32{
		"ARGUMENTS_MISSING": 0,
		"TARGETS_MISSING":   1,
		"ALREADY_RUNNING":   2,
		"UNKNOWN":           3,
	}
)

func (x OperationRequestFailedError) Enum() *OperationRequestFailedError {
	p := new(OperationRequestFailedError)
	*p = x
	return p
}

func (x OperationRequestFailedError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationRequestFailedError) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_operation_completed_proto_enumTypes[1].Descriptor()
}

func (OperationRequestFailedError) Type() protoreflect.EnumType {
	return &file_protobuf_operation_completed_proto_enumTypes[1]
}

func (x OperationRequestFailedError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationRequestFailedError.Descriptor instead.
func (OperationRequestFailedError) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_operation_completed_proto_rawDescGZIP(), []int{1}
}

type OperationErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	TargetErrors  map[string]string      `protobuf:"bytes,2,rep,name=target_errors,json=targetErrors,proto3" json:"target_errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationErrorDetails) Reset() {
	*x = OperationErrorDetails{}
	mi := &file_protobuf_operation_completed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationErrorDetails) ProtoMessage() {}

func (x *OperationErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_completed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationErrorDetails.ProtoReflect.Descriptor instead.
func (*OperationErrorDetails) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_completed_proto_rawDescGZIP(), []int{0}
}

func (x *OperationErrorDetails) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *OperationErrorDetails) GetTargetErrors() map[string]string {
	if x != nil {
		return x.TargetErrors
	}
	return nil
}

type OperationRequestFailedDetails struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Error         OperationRequestFailedError `protobuf:"varint,1,opt,name=error,proto3,enum=Trento.Operations.V1.OperationRequestFailedError" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequestFailedDetails) Reset() {
	*x = OperationRequestFailedDetails{}
	mi := &file_protobuf_operation_completed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequestFailedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequestFailedDetails) ProtoMessage() {}

func (x *OperationRequestFailedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_completed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequestFailedDetails.ProtoReflect.Descriptor instead.
func (*OperationRequestFailedDetails) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_completed_proto_rawDescGZIP(), []int{1}
}

func (x *OperationRequestFailedDetails) GetError() OperationRequestFailedError {
	if x != nil {
		return x.Error
	}
	return OperationRequestFailedError_ARGUMENTS_MISSING
}

type OperationCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperationType string                 `protobuf:"bytes,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Result        OperationResult        `protobuf:"varint,4,opt,name=result,proto3,enum=Trento.Operations.V1.OperationResult" json:"result,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*OperationCompleted_ErrorDetails
	//	*OperationCompleted_RequestFailedDetails
	Details       isOperationCompleted_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationCompleted) Reset() {
	*x = OperationCompleted{}
	mi := &file_protobuf_operation_completed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationCompleted) ProtoMessage() {}

func (x *OperationCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_completed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationCompleted.ProtoReflect.Descriptor instead.
func (*OperationCompleted) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_completed_proto_rawDescGZIP(), []int{2}
}

func (x *OperationCompleted) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationCompleted) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *OperationCompleted) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *OperationCompleted) GetResult() OperationResult {
	if x != nil {
		return x.Result
	}
	return OperationResult_UPDATED
}

func (x *OperationCompleted) GetDetails() isOperationCompleted_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *OperationCompleted) GetErrorDetails() *OperationErrorDetails {
	if x != nil {
		if x, ok := x.Details.(*OperationCompleted_ErrorDetails); ok {
			return x.ErrorDetails
		}
	}
	return nil
}

func (x *OperationCompleted) GetRequestFailedDetails() *OperationRequestFailedDetails {
	if x != nil {
		if x, ok := x.Details.(*OperationCompleted_RequestFailedDetails); ok {
			return x.RequestFailedDetails
		}
	}
	return nil
}

type isOperationCompleted_Details interface {
	isOperationCompleted_Details()
}

type OperationCompleted_ErrorDetails struct {
	ErrorDetails *OperationErrorDetails `protobuf:"bytes,5,opt,name=error_details,json=errorDetails,proto3,oneof"`
}

type OperationCompleted_RequestFailedDetails struct {
	RequestFailedDetails *OperationRequestFailedDetails `protobuf:"bytes,6,opt,name=request_failed_details,json=requestFailedDetails,proto3,oneof"`
}

func (*OperationCompleted_ErrorDetails) isOperationCompleted_Details() {}

func (*OperationCompleted_RequestFailedDetails) isOperationCompleted_Details() {}

var File_protobuf_operation_completed_proto protoreflect.FileDescriptor

const file_protobuf_operation_completed_proto_rawDesc = "" +
	"\n" +
	"\"protobuf/operation_completed.proto\x12\x14Trento.Operations.V1\"\xd0\x01\n" +
	"\x15OperationErrorDetails\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12b\n" +
	"\rtarget_errors\x18\x02 \x03(\v2=.Trento.Operations.V1.OperationErrorDetails.TargetErrorsEntryR\ftargetErrors\x1a?\n" +
	"\x11TargetErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x1dOperationRequestFailedDetails\x12G\n" +
	"\x05error\x18\x01 \x01(\x0e21.Trento.Operations.V1.OperationRequestFailedErrorR\x05error\"\x84\x03\n" +
	"\x12OperationCompleted\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12%\n" +
	"\x0eoperation_type\x18\x03 \x01(\tR\roperationType\x12=\n" +
	"\x06result\x18\x04 \x01(\x0e2%.Trento.Operations.V1.OperationResultR\x06result\x12R\n" +
	"\rerror_details\x18\x05 \x01(\v2+.Trento.Operations.V1.OperationErrorDetailsH\x00R\ferrorDetails\x12k\n" +
	"\x16request_failed_details\x18\x06 \x01(\v23.Trento.Operations.V1.OperationRequestFailedDetailsH\x00R\x14requestFailedDetailsB\t\n" +
	"\adetails*s\n" +
	"\x0fOperationResult\x12\v\n" +
	"\aUPDATED\x10\x00\x12\x0f\n" +
	"\vNOT_UPDATED\x10\x01\x12\x0f\n" +
	"\vROLLED_BACK\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\v\n" +
	"\aABORTED\x10\x04\x12\x12\n" +
	"\x0eREQUEST_FAILED\x10\x06\"\x04\b\x05\x10\x05*k\n" +
	"\x1bOperationRequestFailedError\x12\x15\n" +
	"\x11ARGUMENTS_MISSING\x10\x00\x12\x13\n" +
	"\x0fTARGETS_MISSING\x10\x01\x12\x13\n" +
	"\x0fALREADY_RUNNING\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x03B\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_operation_completed_proto_rawDescOnce sync.Once
	file_protobuf_operation_completed_proto_rawDescData []byte
)

func file_protobuf_operation_completed_proto_rawDescGZIP() []byte {
	file_protobuf_operation_completed_proto_rawDescOnce.Do(func() {
		file_protobuf_operation_completed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_operation_completed_proto_rawDesc), len(file_protobuf_operation_completed_proto_rawDesc)))
	})
	return file_protobuf_operation_completed_proto_rawDescData
}

var file_protobuf_operation_completed_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_operation_completed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_operation_completed_proto_goTypes = []any{
	(OperationResult)(0),                  // 0: Trento.Operations.V1.OperationResult
	(OperationRequestFailedError)(0),      // 1: Trento.Operations.V1.OperationRequestFailedError
	(*OperationErrorDetails)(nil),         // 2: Trento.Operations.V1.OperationErrorDetails
	(*OperationRequestFailedDetails)(nil), // 3: Trento.Operations.V1.OperationRequestFailedDetails
	(*OperationCompleted)(nil),            // 4: Trento.Operations.V1.OperationCompleted
	nil,                                   // 5: Trento.Operations.V1.OperationErrorDetails.TargetErrorsEntry
}
var file_protobuf_operation_completed_proto_depIdxs = []int32{
	5, // 0: Trento.Operations.V1.OperationErrorDetails.target_errors:type_name -> Trento.Operations.V1.OperationErrorDetails.TargetErrorsEntry
	1, // 1: Trento.Operations.V1.OperationRequestFailedDetails.error:type_name -> Trento.Operations.V1.OperationRequestFailedError
	0, // 2: Trento.Operations.V1.OperationCompleted.result:type_name -> Trento.Operations.V1.OperationResult
	2, // 3: Trento.Operations.V1.OperationCompleted.error_details:type_name -> Trento.Operations.V1.OperationErrorDetails
	3, // 4: Trento.Operations.V1.OperationCompleted.request_failed_details:type_name -> Trento.Operations.V1.OperationRequestFailedDetails
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_operation_completed_proto_init() }
func file_protobuf_operation_completed_proto_init() {
	if File_protobuf_operation_completed_proto != nil {
		return
	}
	file_protobuf_operation_completed_proto_msgTypes[2].OneofWrappers = []any{
		(*OperationCompleted_ErrorDetails)(nil),
		(*OperationCompleted_RequestFailedDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_operation_completed_proto_rawDesc), len(file_protobuf_operation_completed_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operation_completed_proto_goTypes,
		DependencyIndexes: file_protobuf_operation_completed_proto_depIdxs,
		EnumInfos:         file_protobuf_operation_completed_proto_enumTypes,
		MessageInfos:      file_protobuf_operation_completed_proto_msgTypes,
	}.Build()
	File_protobuf_operation_completed_proto = out.File
	file_protobuf_operation_completed_proto_goTypes = nil
	file_protobuf_operation_completed_proto_depIdxs = nil
}
