// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/operator_execution_requested.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorExecutionRequestedTarget struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	AgentId       string                     `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Arguments     map[string]*structpb.Value `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorExecutionRequestedTarget) Reset() {
	*x = OperatorExecutionRequestedTarget{}
	mi := &file_protobuf_operator_execution_requested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorExecutionRequestedTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorExecutionRequestedTarget) ProtoMessage() {}

func (x *OperatorExecutionRequestedTarget) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_requested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorExecutionRequestedTarget.ProtoReflect.Descriptor instead.
func (*OperatorExecutionRequestedTarget) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_requested_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorExecutionRequestedTarget) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *OperatorExecutionRequestedTarget) GetArguments() map[string]*structpb.Value {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type OperatorExecutionRequested struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	OperationId   string                              `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	GroupId       string                              `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	StepNumber    int32                               `protobuf:"varint,3,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	Operator      string                              `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Targets       []*OperatorExecutionRequestedTarget `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorExecutionRequested) Reset() {
	*x = OperatorExecutionRequested{}
	mi := &file_protobuf_operator_execution_requested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorExecutionRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorExecutionRequested) ProtoMessage() {}

func (x *OperatorExecutionRequested) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_requested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorExecutionRequested.ProtoReflect.Descriptor instead.
func (*OperatorExecutionRequested) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_requested_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorExecutionRequested) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperatorExecutionRequested) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *OperatorExecutionRequested) GetStepNumber() int32 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *OperatorExecutionRequested) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OperatorExecutionRequested) GetTargets() []*OperatorExecutionRequestedTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_protobuf_operator_execution_requested_proto protoreflect.FileDescriptor

const file_protobuf_operator_execution_requested_proto_rawDesc = "" +
	"\n" +
	"+protobuf/operator_execution_requested.proto\x12\x14Trento.Operations.V1\x1a\x1cgoogle/protobuf/struct.proto\"\xf8\x01\n" +
	" OperatorExecutionRequestedTarget\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12c\n" +
	"\targuments\x18\x02 \x03(\v2E.Trento.Operations.V1.OperatorExecutionRequestedTarget.ArgumentsEntryR\targuments\x1aT\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xe9\x01\n" +
	"\x1aOperatorExecutionRequested\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1f\n" +
	"\vstep_number\x18\x03 \x01(\x05R\n" +
	"stepNumber\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12P\n" +
	"\atargets\x18\x05 \x03(\v26.Trento.Operations.V1.OperatorExecutionRequestedTargetR\atargetsB\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_operator_execution_requested_proto_rawDescOnce sync.Once
	file_protobuf_operator_execution_requested_proto_rawDescData []byte
)

func file_protobuf_operator_execution_requested_proto_rawDescGZIP() []byte {
	file_protobuf_operator_execution_requested_proto_rawDescOnce.Do(func() {
		file_protobuf_operator_execution_requested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_operator_execution_requested_proto_rawDesc), len(file_protobuf_operator_execution_requested_proto_rawDesc)))
	})
	return file_protobuf_operator_execution_requested_proto_rawDescData
}

var file_protobuf_operator_execution_requested_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_operator_execution_requested_proto_goTypes = []any{
	(*OperatorExecutionRequestedTarget)(nil), // 0: Trento.Operations.V1.OperatorExecutionRequestedTarget
	(*OperatorExecutionRequested)(nil),       // 1: Trento.Operations.V1.OperatorExecutionRequested
	nil,                                      // 2: Trento.Operations.V1.OperatorExecutionRequestedTarget.ArgumentsEntry
	(*structpb.Value)(nil),                   // 3: google.protobuf.Value
}
var file_protobuf_operator_execution_requested_proto_depIdxs = []int32{
	2, // 0: Trento.Operations.V1.OperatorExecutionRequestedTarget.arguments:type_name -> Trento.Operations.V1.OperatorExecutionRequestedTarget.ArgumentsEntry
	0, // 1: Trento.Operations.V1.OperatorExecutionRequested.targets:type_name -> Trento.Operations.V1.OperatorExecutionRequestedTarget
	3, // 2: Trento.Operations.V1.OperatorExecutionRequestedTarget.ArgumentsEntry.value:type_name -> google.protobuf.Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_operator_execution_requested_proto_init() }
func file_protobuf_operator_execution_requested_proto_init() {
	if File_protobuf_operator_execution_requested_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_operator_execution_requested_proto_rawDesc), len(file_protobuf_operator_execution_requested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operator_execution_requested_proto_goTypes,
		DependencyIndexes: file_protobuf_operator_execution_requested_proto_depIdxs,
		MessageInfos:      file_protobuf_operator_execution_requested_proto_msgTypes,
	}.Build()
	File_protobuf_operator_execution_requested_proto = out.File
	file_protobuf_operator_execution_requested_proto_goTypes = nil
	file_protobuf_operator_execution_requested_proto_depIdxs = nil
}
