// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.1
// source: protobuf/operation_target.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId   string                     `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Arguments map[string]*structpb.Value `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OperationTarget) Reset() {
	*x = OperationTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operation_target_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationTarget) ProtoMessage() {}

func (x *OperationTarget) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_target_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationTarget.ProtoReflect.Descriptor instead.
func (*OperationTarget) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_target_proto_rawDescGZIP(), []int{0}
}

func (x *OperationTarget) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *OperationTarget) GetArguments() map[string]*structpb.Value {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_protobuf_operation_target_proto protoreflect.FileDescriptor

var file_protobuf_operation_target_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x14, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x52, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x41,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x61,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x54, 0x0a, 0x0e, 0x41, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0a,
	0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_operation_target_proto_rawDescOnce sync.Once
	file_protobuf_operation_target_proto_rawDescData = file_protobuf_operation_target_proto_rawDesc
)

func file_protobuf_operation_target_proto_rawDescGZIP() []byte {
	file_protobuf_operation_target_proto_rawDescOnce.Do(func() {
		file_protobuf_operation_target_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_operation_target_proto_rawDescData)
	})
	return file_protobuf_operation_target_proto_rawDescData
}

var file_protobuf_operation_target_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_operation_target_proto_goTypes = []interface{}{
	(*OperationTarget)(nil), // 0: Trento.Operations.V1.OperationTarget
	nil,                     // 1: Trento.Operations.V1.OperationTarget.ArgumentsEntry
	(*structpb.Value)(nil),  // 2: google.protobuf.Value
}
var file_protobuf_operation_target_proto_depIdxs = []int32{
	1, // 0: Trento.Operations.V1.OperationTarget.arguments:type_name -> Trento.Operations.V1.OperationTarget.ArgumentsEntry
	2, // 1: Trento.Operations.V1.OperationTarget.ArgumentsEntry.value:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_operation_target_proto_init() }
func file_protobuf_operation_target_proto_init() {
	if File_protobuf_operation_target_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_operation_target_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_operation_target_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operation_target_proto_goTypes,
		DependencyIndexes: file_protobuf_operation_target_proto_depIdxs,
		MessageInfos:      file_protobuf_operation_target_proto_msgTypes,
	}.Build()
	File_protobuf_operation_target_proto = out.File
	file_protobuf_operation_target_proto_rawDesc = nil
	file_protobuf_operation_target_proto_goTypes = nil
	file_protobuf_operation_target_proto_depIdxs = nil
}
