// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/operation_execution_completed.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorPhase int32

const (
	ErrorPhase_PLAN     ErrorPhase = 0
	ErrorPhase_COMMIT   ErrorPhase = 1
	ErrorPhase_VERIFY   ErrorPhase = 2
	ErrorPhase_ROLLBACK ErrorPhase = 3
)

// Enum value maps for ErrorPhase.
var (
	ErrorPhase_name = map[int32]string{
		0: "PLAN",
		1: "COMMIT",
		2: "VERIFY",
		3: "ROLLBACK",
	}
	ErrorPhase_value = map[string]int32{
		"PLAN":     0,
		"COMMIT":   1,
		"VERIFY":   2,
		"ROLLBACK": 3,
	}
)

func (x ErrorPhase) Enum() *ErrorPhase {
	p := new(ErrorPhase)
	*p = x
	return p
}

func (x ErrorPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_operation_execution_completed_proto_enumTypes[0].Descriptor()
}

func (ErrorPhase) Type() protoreflect.EnumType {
	return &file_protobuf_operation_execution_completed_proto_enumTypes[0]
}

func (x ErrorPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorPhase.Descriptor instead.
func (ErrorPhase) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_operation_execution_completed_proto_rawDescGZIP(), []int{0}
}

type OperationReportError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrorPhase ErrorPhase `protobuf:"varint,2,opt,name=error_phase,json=errorPhase,proto3,enum=Trento.Operations.V1.ErrorPhase" json:"error_phase,omitempty"`
}

func (x *OperationReportError) Reset() {
	*x = OperationReportError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operation_execution_completed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationReportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationReportError) ProtoMessage() {}

func (x *OperationReportError) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_execution_completed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationReportError.ProtoReflect.Descriptor instead.
func (*OperationReportError) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_execution_completed_proto_rawDescGZIP(), []int{0}
}

func (x *OperationReportError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationReportError) GetErrorPhase() ErrorPhase {
	if x != nil {
		return x.ErrorPhase
	}
	return ErrorPhase_PLAN
}

type OperationReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diff map[string]string `protobuf:"bytes,1,rep,name=diff,proto3" json:"diff,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OperationReportResponse) Reset() {
	*x = OperationReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operation_execution_completed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationReportResponse) ProtoMessage() {}

func (x *OperationReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_execution_completed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationReportResponse.ProtoReflect.Descriptor instead.
func (*OperationReportResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_execution_completed_proto_rawDescGZIP(), []int{1}
}

func (x *OperationReportResponse) GetDiff() map[string]string {
	if x != nil {
		return x.Diff
	}
	return nil
}

type OperationExecutionReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	AgentId     string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are assignable to OperationResult:
	//	*OperationExecutionReport_Response
	//	*OperationExecutionReport_ErrorValue
	OperationResult isOperationExecutionReport_OperationResult `protobuf_oneof:"operation_result"`
}

func (x *OperationExecutionReport) Reset() {
	*x = OperationExecutionReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operation_execution_completed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationExecutionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationExecutionReport) ProtoMessage() {}

func (x *OperationExecutionReport) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_execution_completed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationExecutionReport.ProtoReflect.Descriptor instead.
func (*OperationExecutionReport) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_execution_completed_proto_rawDescGZIP(), []int{2}
}

func (x *OperationExecutionReport) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationExecutionReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (m *OperationExecutionReport) GetOperationResult() isOperationExecutionReport_OperationResult {
	if m != nil {
		return m.OperationResult
	}
	return nil
}

func (x *OperationExecutionReport) GetResponse() *OperationReportResponse {
	if x, ok := x.GetOperationResult().(*OperationExecutionReport_Response); ok {
		return x.Response
	}
	return nil
}

func (x *OperationExecutionReport) GetErrorValue() *OperationReportError {
	if x, ok := x.GetOperationResult().(*OperationExecutionReport_ErrorValue); ok {
		return x.ErrorValue
	}
	return nil
}

type isOperationExecutionReport_OperationResult interface {
	isOperationExecutionReport_OperationResult()
}

type OperationExecutionReport_Response struct {
	Response *OperationReportResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type OperationExecutionReport_ErrorValue struct {
	ErrorValue *OperationReportError `protobuf:"bytes,4,opt,name=error_value,json=errorValue,proto3,oneof"`
}

func (*OperationExecutionReport_Response) isOperationExecutionReport_OperationResult() {}

func (*OperationExecutionReport_ErrorValue) isOperationExecutionReport_OperationResult() {}

var File_protobuf_operation_execution_completed_proto protoreflect.FileDescriptor

var file_protobuf_operation_execution_completed_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x56, 0x31, 0x22, 0x73, 0x0a, 0x14, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x54, 0x72,
	0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x56, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x0a, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x17, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x64, 0x69, 0x66, 0x66, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x69,
	0x66, 0x66, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x69, 0x66, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x88, 0x02, 0x0a, 0x18,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74,
	0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74,
	0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x3c, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4c, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x45,
	0x52, 0x49, 0x46, 0x59, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x4f, 0x4c, 0x4c, 0x42, 0x41,
	0x43, 0x4b, 0x10, 0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_operation_execution_completed_proto_rawDescOnce sync.Once
	file_protobuf_operation_execution_completed_proto_rawDescData = file_protobuf_operation_execution_completed_proto_rawDesc
)

func file_protobuf_operation_execution_completed_proto_rawDescGZIP() []byte {
	file_protobuf_operation_execution_completed_proto_rawDescOnce.Do(func() {
		file_protobuf_operation_execution_completed_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_operation_execution_completed_proto_rawDescData)
	})
	return file_protobuf_operation_execution_completed_proto_rawDescData
}

var file_protobuf_operation_execution_completed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_operation_execution_completed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_operation_execution_completed_proto_goTypes = []interface{}{
	(ErrorPhase)(0),                  // 0: Trento.Operations.V1.ErrorPhase
	(*OperationReportError)(nil),     // 1: Trento.Operations.V1.OperationReportError
	(*OperationReportResponse)(nil),  // 2: Trento.Operations.V1.OperationReportResponse
	(*OperationExecutionReport)(nil), // 3: Trento.Operations.V1.OperationExecutionReport
	nil,                              // 4: Trento.Operations.V1.OperationReportResponse.DiffEntry
}
var file_protobuf_operation_execution_completed_proto_depIdxs = []int32{
	0, // 0: Trento.Operations.V1.OperationReportError.error_phase:type_name -> Trento.Operations.V1.ErrorPhase
	4, // 1: Trento.Operations.V1.OperationReportResponse.diff:type_name -> Trento.Operations.V1.OperationReportResponse.DiffEntry
	2, // 2: Trento.Operations.V1.OperationExecutionReport.response:type_name -> Trento.Operations.V1.OperationReportResponse
	1, // 3: Trento.Operations.V1.OperationExecutionReport.error_value:type_name -> Trento.Operations.V1.OperationReportError
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_operation_execution_completed_proto_init() }
func file_protobuf_operation_execution_completed_proto_init() {
	if File_protobuf_operation_execution_completed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_operation_execution_completed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationReportError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_operation_execution_completed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_operation_execution_completed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationExecutionReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_operation_execution_completed_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*OperationExecutionReport_Response)(nil),
		(*OperationExecutionReport_ErrorValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_operation_execution_completed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operation_execution_completed_proto_goTypes,
		DependencyIndexes: file_protobuf_operation_execution_completed_proto_depIdxs,
		EnumInfos:         file_protobuf_operation_execution_completed_proto_enumTypes,
		MessageInfos:      file_protobuf_operation_execution_completed_proto_msgTypes,
	}.Build()
	File_protobuf_operation_execution_completed_proto = out.File
	file_protobuf_operation_execution_completed_proto_rawDesc = nil
	file_protobuf_operation_execution_completed_proto_goTypes = nil
	file_protobuf_operation_execution_completed_proto_depIdxs = nil
}
