// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/operation_started.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperationType string                 `protobuf:"bytes,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Targets       []*OperationTarget     `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStarted) Reset() {
	*x = OperationStarted{}
	mi := &file_protobuf_operation_started_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStarted) ProtoMessage() {}

func (x *OperationStarted) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_started_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStarted.ProtoReflect.Descriptor instead.
func (*OperationStarted) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_started_proto_rawDescGZIP(), []int{0}
}

func (x *OperationStarted) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationStarted) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *OperationStarted) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *OperationStarted) GetTargets() []*OperationTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_protobuf_operation_started_proto protoreflect.FileDescriptor

const file_protobuf_operation_started_proto_rawDesc = "" +
	"\n" +
	" protobuf/operation_started.proto\x12\x14Trento.Operations.V1\x1a\x1fprotobuf/operation_target.proto\"\xb8\x01\n" +
	"\x10OperationStarted\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12%\n" +
	"\x0eoperation_type\x18\x03 \x01(\tR\roperationType\x12?\n" +
	"\atargets\x18\x04 \x03(\v2%.Trento.Operations.V1.OperationTargetR\atargetsB\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_operation_started_proto_rawDescOnce sync.Once
	file_protobuf_operation_started_proto_rawDescData []byte
)

func file_protobuf_operation_started_proto_rawDescGZIP() []byte {
	file_protobuf_operation_started_proto_rawDescOnce.Do(func() {
		file_protobuf_operation_started_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_operation_started_proto_rawDesc), len(file_protobuf_operation_started_proto_rawDesc)))
	})
	return file_protobuf_operation_started_proto_rawDescData
}

var file_protobuf_operation_started_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_operation_started_proto_goTypes = []any{
	(*OperationStarted)(nil), // 0: Trento.Operations.V1.OperationStarted
	(*OperationTarget)(nil),  // 1: Trento.Operations.V1.OperationTarget
}
var file_protobuf_operation_started_proto_depIdxs = []int32{
	1, // 0: Trento.Operations.V1.OperationStarted.targets:type_name -> Trento.Operations.V1.OperationTarget
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_operation_started_proto_init() }
func file_protobuf_operation_started_proto_init() {
	if File_protobuf_operation_started_proto != nil {
		return
	}
	file_protobuf_operation_target_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_operation_started_proto_rawDesc), len(file_protobuf_operation_started_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operation_started_proto_goTypes,
		DependencyIndexes: file_protobuf_operation_started_proto_depIdxs,
		MessageInfos:      file_protobuf_operation_started_proto_msgTypes,
	}.Build()
	File_protobuf_operation_started_proto = out.File
	file_protobuf_operation_started_proto_goTypes = nil
	file_protobuf_operation_started_proto_depIdxs = nil
}
