// SPDX-FileCopyrightText: SUSE LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: protobuf/operator_execution_completed.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorPhase int32

const (
	OperatorPhase_PLAN     OperatorPhase = 0
	OperatorPhase_COMMIT   OperatorPhase = 1
	OperatorPhase_VERIFY   OperatorPhase = 2
	OperatorPhase_ROLLBACK OperatorPhase = 3
)

// Enum value maps for OperatorPhase.
var (
	OperatorPhase_name = map[int32]string{
		0: "PLAN",
		1: "COMMIT",
		2: "VERIFY",
		3: "ROLLBACK",
	}
	OperatorPhase_value = map[string]int32{
		"PLAN":     0,
		"COMMIT":   1,
		"VERIFY":   2,
		"ROLLBACK": 3,
	}
)

func (x OperatorPhase) Enum() *OperatorPhase {
	p := new(OperatorPhase)
	*p = x
	return p
}

func (x OperatorPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_operator_execution_completed_proto_enumTypes[0].Descriptor()
}

func (OperatorPhase) Type() protoreflect.EnumType {
	return &file_protobuf_operator_execution_completed_proto_enumTypes[0]
}

func (x OperatorPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorPhase.Descriptor instead.
func (OperatorPhase) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{0}
}

type OperatorDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *structpb.Value        `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After         *structpb.Value        `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorDiff) Reset() {
	*x = OperatorDiff{}
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorDiff) ProtoMessage() {}

func (x *OperatorDiff) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorDiff.ProtoReflect.Descriptor instead.
func (*OperatorDiff) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorDiff) GetBefore() *structpb.Value {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *OperatorDiff) GetAfter() *structpb.Value {
	if x != nil {
		return x.After
	}
	return nil
}

type OperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         OperatorPhase          `protobuf:"varint,1,opt,name=phase,proto3,enum=Trento.Operations.V1.OperatorPhase" json:"phase,omitempty"`
	Diff          *OperatorDiff          `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorResponse) Reset() {
	*x = OperatorResponse{}
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorResponse) ProtoMessage() {}

func (x *OperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorResponse.ProtoReflect.Descriptor instead.
func (*OperatorResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorResponse) GetPhase() OperatorPhase {
	if x != nil {
		return x.Phase
	}
	return OperatorPhase_PLAN
}

func (x *OperatorResponse) GetDiff() *OperatorDiff {
	if x != nil {
		return x.Diff
	}
	return nil
}

type OperatorError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         OperatorPhase          `protobuf:"varint,1,opt,name=phase,proto3,enum=Trento.Operations.V1.OperatorPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorError) Reset() {
	*x = OperatorError{}
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorError) ProtoMessage() {}

func (x *OperatorError) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorError.ProtoReflect.Descriptor instead.
func (*OperatorError) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{2}
}

func (x *OperatorError) GetPhase() OperatorPhase {
	if x != nil {
		return x.Phase
	}
	return OperatorPhase_PLAN
}

func (x *OperatorError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OperatorExecutionCompleted struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OperationId string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	GroupId     string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	StepNumber  int32                  `protobuf:"varint,3,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	AgentId     string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*OperatorExecutionCompleted_Value
	//	*OperatorExecutionCompleted_Error
	Result        isOperatorExecutionCompleted_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorExecutionCompleted) Reset() {
	*x = OperatorExecutionCompleted{}
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorExecutionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorExecutionCompleted) ProtoMessage() {}

func (x *OperatorExecutionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorExecutionCompleted.ProtoReflect.Descriptor instead.
func (*OperatorExecutionCompleted) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{3}
}

func (x *OperatorExecutionCompleted) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperatorExecutionCompleted) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *OperatorExecutionCompleted) GetStepNumber() int32 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *OperatorExecutionCompleted) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *OperatorExecutionCompleted) GetResult() isOperatorExecutionCompleted_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *OperatorExecutionCompleted) GetValue() *OperatorResponse {
	if x != nil {
		if x, ok := x.Result.(*OperatorExecutionCompleted_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *OperatorExecutionCompleted) GetError() *OperatorError {
	if x != nil {
		if x, ok := x.Result.(*OperatorExecutionCompleted_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOperatorExecutionCompleted_Result interface {
	isOperatorExecutionCompleted_Result()
}

type OperatorExecutionCompleted_Value struct {
	Value *OperatorResponse `protobuf:"bytes,5,opt,name=value,proto3,oneof"`
}

type OperatorExecutionCompleted_Error struct {
	Error *OperatorError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*OperatorExecutionCompleted_Value) isOperatorExecutionCompleted_Result() {}

func (*OperatorExecutionCompleted_Error) isOperatorExecutionCompleted_Result() {}

var File_protobuf_operator_execution_completed_proto protoreflect.FileDescriptor

const file_protobuf_operator_execution_completed_proto_rawDesc = "" +
	"\n" +
	"+protobuf/operator_execution_completed.proto\x12\x14Trento.Operations.V1\x1a\x1cgoogle/protobuf/struct.proto\"l\n" +
	"\fOperatorDiff\x12.\n" +
	"\x06before\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06before\x12,\n" +
	"\x05after\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05after\"\x85\x01\n" +
	"\x10OperatorResponse\x129\n" +
	"\x05phase\x18\x01 \x01(\x0e2#.Trento.Operations.V1.OperatorPhaseR\x05phase\x126\n" +
	"\x04diff\x18\x02 \x01(\v2\".Trento.Operations.V1.OperatorDiffR\x04diff\"d\n" +
	"\rOperatorError\x129\n" +
	"\x05phase\x18\x01 \x01(\x0e2#.Trento.Operations.V1.OperatorPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9d\x02\n" +
	"\x1aOperatorExecutionCompleted\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1f\n" +
	"\vstep_number\x18\x03 \x01(\x05R\n" +
	"stepNumber\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12>\n" +
	"\x05value\x18\x05 \x01(\v2&.Trento.Operations.V1.OperatorResponseH\x00R\x05value\x12;\n" +
	"\x05error\x18\x06 \x01(\v2#.Trento.Operations.V1.OperatorErrorH\x00R\x05errorB\b\n" +
	"\x06result*?\n" +
	"\rOperatorPhase\x12\b\n" +
	"\x04PLAN\x10\x00\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x01\x12\n" +
	"\n" +
	"\x06VERIFY\x10\x02\x12\f\n" +
	"\bROLLBACK\x10\x03B\n" +
	"Z\b/;eventsb\x06proto3"

var (
	file_protobuf_operator_execution_completed_proto_rawDescOnce sync.Once
	file_protobuf_operator_execution_completed_proto_rawDescData []byte
)

func file_protobuf_operator_execution_completed_proto_rawDescGZIP() []byte {
	file_protobuf_operator_execution_completed_proto_rawDescOnce.Do(func() {
		file_protobuf_operator_execution_completed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_operator_execution_completed_proto_rawDesc), len(file_protobuf_operator_execution_completed_proto_rawDesc)))
	})
	return file_protobuf_operator_execution_completed_proto_rawDescData
}

var file_protobuf_operator_execution_completed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_operator_execution_completed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_operator_execution_completed_proto_goTypes = []any{
	(OperatorPhase)(0),                 // 0: Trento.Operations.V1.OperatorPhase
	(*OperatorDiff)(nil),               // 1: Trento.Operations.V1.OperatorDiff
	(*OperatorResponse)(nil),           // 2: Trento.Operations.V1.OperatorResponse
	(*OperatorError)(nil),              // 3: Trento.Operations.V1.OperatorError
	(*OperatorExecutionCompleted)(nil), // 4: Trento.Operations.V1.OperatorExecutionCompleted
	(*structpb.Value)(nil),             // 5: google.protobuf.Value
}
var file_protobuf_operator_execution_completed_proto_depIdxs = []int32{
	5, // 0: Trento.Operations.V1.OperatorDiff.before:type_name -> google.protobuf.Value
	5, // 1: Trento.Operations.V1.OperatorDiff.after:type_name -> google.protobuf.Value
	0, // 2: Trento.Operations.V1.OperatorResponse.phase:type_name -> Trento.Operations.V1.OperatorPhase
	1, // 3: Trento.Operations.V1.OperatorResponse.diff:type_name -> Trento.Operations.V1.OperatorDiff
	0, // 4: Trento.Operations.V1.OperatorError.phase:type_name -> Trento.Operations.V1.OperatorPhase
	2, // 5: Trento.Operations.V1.OperatorExecutionCompleted.value:type_name -> Trento.Operations.V1.OperatorResponse
	3, // 6: Trento.Operations.V1.OperatorExecutionCompleted.error:type_name -> Trento.Operations.V1.OperatorError
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_operator_execution_completed_proto_init() }
func file_protobuf_operator_execution_completed_proto_init() {
	if File_protobuf_operator_execution_completed_proto != nil {
		return
	}
	file_protobuf_operator_execution_completed_proto_msgTypes[3].OneofWrappers = []any{
		(*OperatorExecutionCompleted_Value)(nil),
		(*OperatorExecutionCompleted_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_operator_execution_completed_proto_rawDesc), len(file_protobuf_operator_execution_completed_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operator_execution_completed_proto_goTypes,
		DependencyIndexes: file_protobuf_operator_execution_completed_proto_depIdxs,
		EnumInfos:         file_protobuf_operator_execution_completed_proto_enumTypes,
		MessageInfos:      file_protobuf_operator_execution_completed_proto_msgTypes,
	}.Build()
	File_protobuf_operator_execution_completed_proto = out.File
	file_protobuf_operator_execution_completed_proto_goTypes = nil
	file_protobuf_operator_execution_completed_proto_depIdxs = nil
}
