// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/operator_execution_completed.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorPhase int32

const (
	OperatorPhase_PLAN     OperatorPhase = 0
	OperatorPhase_COMMIT   OperatorPhase = 1
	OperatorPhase_VERIFY   OperatorPhase = 2
	OperatorPhase_ROLLBACK OperatorPhase = 3
)

// Enum value maps for OperatorPhase.
var (
	OperatorPhase_name = map[int32]string{
		0: "PLAN",
		1: "COMMIT",
		2: "VERIFY",
		3: "ROLLBACK",
	}
	OperatorPhase_value = map[string]int32{
		"PLAN":     0,
		"COMMIT":   1,
		"VERIFY":   2,
		"ROLLBACK": 3,
	}
)

func (x OperatorPhase) Enum() *OperatorPhase {
	p := new(OperatorPhase)
	*p = x
	return p
}

func (x OperatorPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_operator_execution_completed_proto_enumTypes[0].Descriptor()
}

func (OperatorPhase) Type() protoreflect.EnumType {
	return &file_protobuf_operator_execution_completed_proto_enumTypes[0]
}

func (x OperatorPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorPhase.Descriptor instead.
func (OperatorPhase) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{0}
}

type OperatorDiff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Before *structpb.Value `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After  *structpb.Value `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
}

func (x *OperatorDiff) Reset() {
	*x = OperatorDiff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operator_execution_completed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorDiff) ProtoMessage() {}

func (x *OperatorDiff) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorDiff.ProtoReflect.Descriptor instead.
func (*OperatorDiff) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorDiff) GetBefore() *structpb.Value {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *OperatorDiff) GetAfter() *structpb.Value {
	if x != nil {
		return x.After
	}
	return nil
}

type OperatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phase OperatorPhase `protobuf:"varint,1,opt,name=phase,proto3,enum=Trento.Operations.V1.OperatorPhase" json:"phase,omitempty"`
	Diff  *OperatorDiff `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
}

func (x *OperatorResponse) Reset() {
	*x = OperatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operator_execution_completed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorResponse) ProtoMessage() {}

func (x *OperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorResponse.ProtoReflect.Descriptor instead.
func (*OperatorResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorResponse) GetPhase() OperatorPhase {
	if x != nil {
		return x.Phase
	}
	return OperatorPhase_PLAN
}

func (x *OperatorResponse) GetDiff() *OperatorDiff {
	if x != nil {
		return x.Diff
	}
	return nil
}

type OperatorError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phase   OperatorPhase `protobuf:"varint,1,opt,name=phase,proto3,enum=Trento.Operations.V1.OperatorPhase" json:"phase,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OperatorError) Reset() {
	*x = OperatorError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operator_execution_completed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorError) ProtoMessage() {}

func (x *OperatorError) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorError.ProtoReflect.Descriptor instead.
func (*OperatorError) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{2}
}

func (x *OperatorError) GetPhase() OperatorPhase {
	if x != nil {
		return x.Phase
	}
	return OperatorPhase_PLAN
}

func (x *OperatorError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OperatorExecutionCompleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	GroupId     string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	StepNumber  int32  `protobuf:"varint,3,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	AgentId     string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are assignable to Result:
	//
	//	*OperatorExecutionCompleted_Value
	//	*OperatorExecutionCompleted_Error
	Result isOperatorExecutionCompleted_Result `protobuf_oneof:"result"`
}

func (x *OperatorExecutionCompleted) Reset() {
	*x = OperatorExecutionCompleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operator_execution_completed_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorExecutionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorExecutionCompleted) ProtoMessage() {}

func (x *OperatorExecutionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operator_execution_completed_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorExecutionCompleted.ProtoReflect.Descriptor instead.
func (*OperatorExecutionCompleted) Descriptor() ([]byte, []int) {
	return file_protobuf_operator_execution_completed_proto_rawDescGZIP(), []int{3}
}

func (x *OperatorExecutionCompleted) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperatorExecutionCompleted) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *OperatorExecutionCompleted) GetStepNumber() int32 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *OperatorExecutionCompleted) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (m *OperatorExecutionCompleted) GetResult() isOperatorExecutionCompleted_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *OperatorExecutionCompleted) GetValue() *OperatorResponse {
	if x, ok := x.GetResult().(*OperatorExecutionCompleted_Value); ok {
		return x.Value
	}
	return nil
}

func (x *OperatorExecutionCompleted) GetError() *OperatorError {
	if x, ok := x.GetResult().(*OperatorExecutionCompleted_Error); ok {
		return x.Error
	}
	return nil
}

type isOperatorExecutionCompleted_Result interface {
	isOperatorExecutionCompleted_Result()
}

type OperatorExecutionCompleted_Value struct {
	Value *OperatorResponse `protobuf:"bytes,5,opt,name=value,proto3,oneof"`
}

type OperatorExecutionCompleted_Error struct {
	Error *OperatorError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*OperatorExecutionCompleted_Value) isOperatorExecutionCompleted_Result() {}

func (*OperatorExecutionCompleted_Error) isOperatorExecutionCompleted_Result() {}

var File_protobuf_operator_execution_completed_proto protoreflect.FileDescriptor

var file_protobuf_operator_execution_completed_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x54,
	0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x56, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6c, 0x0a, 0x0c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x66,
	0x66, 0x12, 0x2e, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72,
	0x65, 0x12, 0x2c, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x22,
	0x85, 0x01, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x04, 0x64, 0x69, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x66,
	0x66, 0x52, 0x04, 0x64, 0x69, 0x66, 0x66, 0x22, 0x64, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x39, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68,
	0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9d, 0x02,
	0x0a, 0x1a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x65, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x3f, 0x0a,
	0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x4c, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d,
	0x49, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x4f, 0x4c, 0x4c, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x03, 0x42, 0x0a,
	0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_operator_execution_completed_proto_rawDescOnce sync.Once
	file_protobuf_operator_execution_completed_proto_rawDescData = file_protobuf_operator_execution_completed_proto_rawDesc
)

func file_protobuf_operator_execution_completed_proto_rawDescGZIP() []byte {
	file_protobuf_operator_execution_completed_proto_rawDescOnce.Do(func() {
		file_protobuf_operator_execution_completed_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_operator_execution_completed_proto_rawDescData)
	})
	return file_protobuf_operator_execution_completed_proto_rawDescData
}

var file_protobuf_operator_execution_completed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_operator_execution_completed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_operator_execution_completed_proto_goTypes = []interface{}{
	(OperatorPhase)(0),                 // 0: Trento.Operations.V1.OperatorPhase
	(*OperatorDiff)(nil),               // 1: Trento.Operations.V1.OperatorDiff
	(*OperatorResponse)(nil),           // 2: Trento.Operations.V1.OperatorResponse
	(*OperatorError)(nil),              // 3: Trento.Operations.V1.OperatorError
	(*OperatorExecutionCompleted)(nil), // 4: Trento.Operations.V1.OperatorExecutionCompleted
	(*structpb.Value)(nil),             // 5: google.protobuf.Value
}
var file_protobuf_operator_execution_completed_proto_depIdxs = []int32{
	5, // 0: Trento.Operations.V1.OperatorDiff.before:type_name -> google.protobuf.Value
	5, // 1: Trento.Operations.V1.OperatorDiff.after:type_name -> google.protobuf.Value
	0, // 2: Trento.Operations.V1.OperatorResponse.phase:type_name -> Trento.Operations.V1.OperatorPhase
	1, // 3: Trento.Operations.V1.OperatorResponse.diff:type_name -> Trento.Operations.V1.OperatorDiff
	0, // 4: Trento.Operations.V1.OperatorError.phase:type_name -> Trento.Operations.V1.OperatorPhase
	2, // 5: Trento.Operations.V1.OperatorExecutionCompleted.value:type_name -> Trento.Operations.V1.OperatorResponse
	3, // 6: Trento.Operations.V1.OperatorExecutionCompleted.error:type_name -> Trento.Operations.V1.OperatorError
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_operator_execution_completed_proto_init() }
func file_protobuf_operator_execution_completed_proto_init() {
	if File_protobuf_operator_execution_completed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_operator_execution_completed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorDiff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_operator_execution_completed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_operator_execution_completed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_operator_execution_completed_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorExecutionCompleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_operator_execution_completed_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*OperatorExecutionCompleted_Value)(nil),
		(*OperatorExecutionCompleted_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_operator_execution_completed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operator_execution_completed_proto_goTypes,
		DependencyIndexes: file_protobuf_operator_execution_completed_proto_depIdxs,
		EnumInfos:         file_protobuf_operator_execution_completed_proto_enumTypes,
		MessageInfos:      file_protobuf_operator_execution_completed_proto_msgTypes,
	}.Build()
	File_protobuf_operator_execution_completed_proto = out.File
	file_protobuf_operator_execution_completed_proto_rawDesc = nil
	file_protobuf_operator_execution_completed_proto_goTypes = nil
	file_protobuf_operator_execution_completed_proto_depIdxs = nil
}
