// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.1
// source: protobuf/operation_completed.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationResult int32

const (
	OperationResult_UPDATED         OperationResult = 0
	OperationResult_NOT_UPDATED     OperationResult = 1
	OperationResult_ROLLED_BACK     OperationResult = 2
	OperationResult_FAILED          OperationResult = 3
	OperationResult_ABORTED         OperationResult = 4
	OperationResult_ALREADY_RUNNING OperationResult = 5
)

// Enum value maps for OperationResult.
var (
	OperationResult_name = map[int32]string{
		0: "UPDATED",
		1: "NOT_UPDATED",
		2: "ROLLED_BACK",
		3: "FAILED",
		4: "ABORTED",
		5: "ALREADY_RUNNING",
	}
	OperationResult_value = map[string]int32{
		"UPDATED":         0,
		"NOT_UPDATED":     1,
		"ROLLED_BACK":     2,
		"FAILED":          3,
		"ABORTED":         4,
		"ALREADY_RUNNING": 5,
	}
)

func (x OperationResult) Enum() *OperationResult {
	p := new(OperationResult)
	*p = x
	return p
}

func (x OperationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_operation_completed_proto_enumTypes[0].Descriptor()
}

func (OperationResult) Type() protoreflect.EnumType {
	return &file_protobuf_operation_completed_proto_enumTypes[0]
}

func (x OperationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationResult.Descriptor instead.
func (OperationResult) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_operation_completed_proto_rawDescGZIP(), []int{0}
}

type OperationCompleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationId   string          `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	GroupId       string          `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperationType string          `protobuf:"bytes,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Result        OperationResult `protobuf:"varint,4,opt,name=result,proto3,enum=Trento.Operations.V1.OperationResult" json:"result,omitempty"`
}

func (x *OperationCompleted) Reset() {
	*x = OperationCompleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_operation_completed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationCompleted) ProtoMessage() {}

func (x *OperationCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_operation_completed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationCompleted.ProtoReflect.Descriptor instead.
func (*OperationCompleted) Descriptor() ([]byte, []int) {
	return file_protobuf_operation_completed_proto_rawDescGZIP(), []int{0}
}

func (x *OperationCompleted) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationCompleted) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *OperationCompleted) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *OperationCompleted) GetResult() OperationResult {
	if x != nil {
		return x.Result
	}
	return OperationResult_UPDATED
}

var File_protobuf_operation_completed_proto protoreflect.FileDescriptor

var file_protobuf_operation_completed_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x22, 0xb8, 0x01, 0x0a, 0x12, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x54, 0x72, 0x65, 0x6e, 0x74, 0x6f, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x31, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x6e, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x44,
	0x5f, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x04,
	0x12, 0x13, 0x0a, 0x0f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x52, 0x55, 0x4e, 0x4e,
	0x49, 0x4e, 0x47, 0x10, 0x05, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_operation_completed_proto_rawDescOnce sync.Once
	file_protobuf_operation_completed_proto_rawDescData = file_protobuf_operation_completed_proto_rawDesc
)

func file_protobuf_operation_completed_proto_rawDescGZIP() []byte {
	file_protobuf_operation_completed_proto_rawDescOnce.Do(func() {
		file_protobuf_operation_completed_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_operation_completed_proto_rawDescData)
	})
	return file_protobuf_operation_completed_proto_rawDescData
}

var file_protobuf_operation_completed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_operation_completed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_operation_completed_proto_goTypes = []interface{}{
	(OperationResult)(0),       // 0: Trento.Operations.V1.OperationResult
	(*OperationCompleted)(nil), // 1: Trento.Operations.V1.OperationCompleted
}
var file_protobuf_operation_completed_proto_depIdxs = []int32{
	0, // 0: Trento.Operations.V1.OperationCompleted.result:type_name -> Trento.Operations.V1.OperationResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_operation_completed_proto_init() }
func file_protobuf_operation_completed_proto_init() {
	if File_protobuf_operation_completed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_operation_completed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationCompleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_operation_completed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_operation_completed_proto_goTypes,
		DependencyIndexes: file_protobuf_operation_completed_proto_depIdxs,
		EnumInfos:         file_protobuf_operation_completed_proto_enumTypes,
		MessageInfos:      file_protobuf_operation_completed_proto_msgTypes,
	}.Build()
	File_protobuf_operation_completed_proto = out.File
	file_protobuf_operation_completed_proto_rawDesc = nil
	file_protobuf_operation_completed_proto_goTypes = nil
	file_protobuf_operation_completed_proto_depIdxs = nil
}
