// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protobuf/target_type.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_CLUSTER                 TargetType = 1
	TargetType_HOST                    TargetType = 2
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "CLUSTER",
		2: "HOST",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"CLUSTER":                 1,
		"HOST":                    2,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_target_type_proto_enumTypes[0].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_protobuf_target_type_proto_enumTypes[0]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_target_type_proto_rawDescGZIP(), []int{0}
}

var File_protobuf_target_type_proto protoreflect.FileDescriptor

var file_protobuf_target_type_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x54, 0x72,
	0x65, 0x6e, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x56, 0x31, 0x2a, 0x40,
	0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17,
	0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x55,
	0x53, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x02,
	0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_target_type_proto_rawDescOnce sync.Once
	file_protobuf_target_type_proto_rawDescData = file_protobuf_target_type_proto_rawDesc
)

func file_protobuf_target_type_proto_rawDescGZIP() []byte {
	file_protobuf_target_type_proto_rawDescOnce.Do(func() {
		file_protobuf_target_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_target_type_proto_rawDescData)
	})
	return file_protobuf_target_type_proto_rawDescData
}

var file_protobuf_target_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_target_type_proto_goTypes = []interface{}{
	(TargetType)(0), // 0: Trento.Checks.V1.TargetType
}
var file_protobuf_target_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_target_type_proto_init() }
func file_protobuf_target_type_proto_init() {
	if File_protobuf_target_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_target_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_target_type_proto_goTypes,
		DependencyIndexes: file_protobuf_target_type_proto_depIdxs,
		EnumInfos:         file_protobuf_target_type_proto_enumTypes,
	}.Build()
	File_protobuf_target_type_proto = out.File
	file_protobuf_target_type_proto_rawDesc = nil
	file_protobuf_target_type_proto_goTypes = nil
	file_protobuf_target_type_proto_depIdxs = nil
}
