# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Contracts CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linter-license-headers:
    name: Check license headers
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        name: Checkout
      - uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
        name: Check license Headers

  setup-env:
    name: Setup Environment
    runs-on: ubuntu-24.04
    outputs:
      ELIXIR_VERSION: ${{ steps.compute.outputs.ELIXIR_VERSION }}
      ERLANG_VERSION: ${{ steps.compute.outputs.ERLANG_VERSION }}
      GOLANG_VERSION: ${{ steps.compute.outputs.GOLANG_VERSION }}
      PROTOC_VERSION: ${{ steps.compute.outputs.PROTOC_VERSION }}
      PROTOC_GEN_GO_VERSION: ${{ steps.compute.outputs.PROTOC_GEN_GO_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Read .tool-versions
        uses: endorama/asdf-parse-tool-versions@e60863920ff5af9bf1c794ffbaaef91384b07eed # v1.6.0

      - name: Compute versions
        id: compute
        run: |
          echo "ELIXIR_VERSION=$ELIXIR_VERSION" >> "$GITHUB_OUTPUT"
          echo "ERLANG_VERSION=$ERLANG_VERSION" >> "$GITHUB_OUTPUT"
          echo "GOLANG_VERSION=$GOLANG_VERSION" >> "$GITHUB_OUTPUT"
          echo "PROTOC_VERSION=$PROTOC_VERSION" >> "$GITHUB_OUTPUT"
          echo "PROTOC_GEN_GO_VERSION=$PROTOC_GEN_GO_VERSION" >> "$GITHUB_OUTPUT"

  elixir-deps:
    name: Elixir dependencies
    needs: [setup-env]
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        id: setup-elixir
        with:
          otp-version: ${{ needs.setup-env.outputs.ERLANG_VERSION }}
          elixir-version: ${{ needs.setup-env.outputs.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: mix-cache
        with:
          path: |
            elixir/deps
            elixir/_build/test
            elixir/priv/plts
          key: ${{ runner.os }}-${{ needs.setup-env.outputs.ERLANG_VERSION }}-${{ needs.setup-env.outputs.ELIXIR_VERSION }}-${{ hashFiles('elixir/mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        working-directory: elixir
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile --warnings-as-errors
          mix dialyzer --plt

  static-code-analysis-elixir:
    name: Static Code Analysis elixir
    needs: [setup-env, elixir-deps]
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        id: setup-elixir
        with:
          otp-version: ${{ needs.setup-env.outputs.ERLANG_VERSION }}
          elixir-version: ${{ needs.setup-env.outputs.ELIXIR_VERSION }}

      - name: Retrieve Elixir Cached Dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: mix-cache
        with:
          path: |
            elixir/deps
            elixir/_build/test
            elixir/priv/plts
          key: ${{ runner.os }}-${{ needs.setup-env.outputs.ERLANG_VERSION }}-${{ needs.setup-env.outputs.ELIXIR_VERSION }}-${{ hashFiles('elixir/mix.lock') }}

      - name: Run Credo
        working-directory: elixir
        run: mix credo

      - name: Check for unused dependencies
        working-directory: elixir
        run: mix deps.unlock --check-unused

      - name: Check elixir Code Format
        working-directory: elixir
        run: ls -la && mix format --check-formatted

      - name: Run Dialyzer
        working-directory: elixir
        run: mix dialyzer

  check-elixir-contracts:
    name: Check elixir contracts
    needs: [setup-env, elixir-deps]
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        id: setup-elixir
        with:
          otp-version: ${{ needs.setup-env.outputs.ERLANG_VERSION }}
          elixir-version: ${{ needs.setup-env.outputs.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: mix-cache
        with:
          path: |
            elixir/deps
            elixir/_build/test
            elixir/priv/plts
          key: ${{ runner.os }}-${{ needs.setup-env.outputs.ERLANG_VERSION }}-${{ needs.setup-env.outputs.ELIXIR_VERSION }}-${{ hashFiles('elixir/mix.lock') }}

      - uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: ${{ needs.setup-env.outputs.PROTOC_VERSION }}

      - name: Install protoc elixir plugin
        run: |
          PROTOBUF_VERSION=$(cd ./elixir && mix run -e "Application.spec(:protobuf, :vsn) |> IO.puts" | tail -n 1)
          mix escript.install --force hex protobuf $PROTOBUF_VERSION
      - name: Add escript bin folder to path
        run: echo "$HOME/.mix/escripts" >> $GITHUB_PATH
      - name: generate contracts
        run: make elixir-generate
      - name: Check for uncommitted schema changes
        run: |
          git add -N elixir/
          git diff
          git diff --quiet
      - name: Git status
        run: git status

  check-go-contracts:
    name: Check go contracts
    needs: [setup-env]
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ needs.setup-env.outputs.GOLANG_VERSION }}

      - uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: ${{ needs.setup-env.outputs.PROTOC_VERSION }}

      - name: Install protoc gen go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v${{ needs.setup-env.outputs.PROTOC_GEN_GO_VERSION }}
      - name: generate contracts
        run: make go-generate
      - name: Check for uncommitted schema changes
        run: |
          git add -N go/
          git diff
          git diff --quiet
      - name: Git status
        run: git status

  test-golang:
    name: Go test
    needs: [setup-env, check-go-contracts]
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ needs.setup-env.outputs.GOLANG_VERSION }}

      - name: Run golang tests
        working-directory: go
        run: go mod download && go test ./...

  test-elixir:
    name: Elixir test
    needs: [setup-env, static-code-analysis-elixir, check-elixir-contracts]
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        id: setup-elixir
        with:
          otp-version: ${{ needs.setup-env.outputs.ERLANG_VERSION }}
          elixir-version: ${{ needs.setup-env.outputs.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: mix-cache
        with:
          path: |
            elixir/deps
            elixir/_build/test
            elixir/priv/plts
          key: ${{ runner.os }}-${{ needs.setup-env.outputs.ERLANG_VERSION }}-${{ needs.setup-env.outputs.ELIXIR_VERSION }}-${{ hashFiles('elixir/mix.lock') }}
      - name: Compile
        working-directory: elixir
        run: mix compile --warnings-as-errors
      - name: Run elixir test
        working-directory: elixir
        run: mix test --warnings-as-errors --color --trace --slowest 10
