name: Contracts CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-go-contracts:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: generate contracts
        run: cd go && make go-generate
      - name: copy contracts to go path
        run: cd go && make make-schemas
      - name: Check for uncommited schema changes
        run: |
          git add -N go/
          git diff --quiet || exit 1 && exit 0
      - name: Git status
        run: git status
